export default [
  {
    name: 'Afghanistan',
    id: 'AFG',
    capital: 'Kabul',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 27657145,
    latlng: [33, 65],
    area: 652230,
    translations: {
      de: 'Afghanistan', es: 'Afganistán', fr: 'Afghanistan', ja: 'アフガニスタン', it: 'Afghanistan', br: 'Afeganistão', pt: 'Afeganistão', nl: 'Afghanistan', hr: 'Afganistan', fa: 'افغانستان',
    },
    flag: 'https://restcountries.eu/data/afg.svg',
  }, {
    name: 'Albania',
    id: 'ALB',
    capital: 'Tirana',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 2886026,
    latlng: [41, 20],
    area: 28748,
    translations: {
      de: 'Albanien', es: 'Albania', fr: 'Albanie', ja: 'アルバニア', it: 'Albania', br: 'Albânia', pt: 'Albânia', nl: 'Albanië', hr: 'Albanija', fa: 'آلبانی',
    },
    flag: 'https://restcountries.eu/data/alb.svg',
  }, {
    name: 'Algeria',
    id: 'DZA',
    capital: 'Algiers',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 40400000,
    latlng: [28, 3],
    area: 2381741,
    translations: {
      de: 'Algerien', es: 'Argelia', fr: 'Algérie', ja: 'アルジェリア', it: 'Algeria', br: 'Argélia', pt: 'Argélia', nl: 'Algerije', hr: 'Alžir', fa: 'الجزایر',
    },
    flag: 'https://restcountries.eu/data/dza.svg',
  }, {
    name: 'Andorra',
    id: 'AND',
    capital: 'Andorra la Vella',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 78014,
    latlng: [42.5, 1.5],
    area: 468,
    translations: {
      de: 'Andorra', es: 'Andorra', fr: 'Andorre', ja: 'アンドラ', it: 'Andorra', br: 'Andorra', pt: 'Andorra', nl: 'Andorra', hr: 'Andora', fa: 'آندورا',
    },
    flag: 'https://restcountries.eu/data/and.svg',
  }, {
    name: 'Angola',
    id: 'AGO',
    capital: 'Luanda',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 25868000,
    latlng: [-12.5, 18.5],
    area: 1246700,
    translations: {
      de: 'Angola', es: 'Angola', fr: 'Angola', ja: 'アンゴラ', it: 'Angola', br: 'Angola', pt: 'Angola', nl: 'Angola', hr: 'Angola', fa: 'آنگولا',
    },
    flag: 'https://restcountries.eu/data/ago.svg',
  }, {
    name: 'Antigua and Barbuda',
    id: 'ATG',
    capital: "Saint John's",
    region: 'Americas',
    subregion: 'Caribbean',
    population: 86295,
    latlng: [17.05, -61.8],
    area: 442,
    translations: {
      de: 'Antigua und Barbuda', es: 'Antigua y Barbuda', fr: 'Antigua-et-Barbuda', ja: 'アンティグア・バーブーダ', it: 'Antigua e Barbuda', br: 'Antígua e Barbuda', pt: 'Antígua e Barbuda', nl: 'Antigua en Barbuda', hr: 'Antigva i Barbuda', fa: 'آنتیگوا و باربودا',
    },
    flag: 'https://restcountries.eu/data/atg.svg',
  }, {
    name: 'Argentina',
    id: 'ARG',
    capital: 'Buenos Aires',
    region: 'Americas',
    subregion: 'South America',
    population: 43590400,
    latlng: [-34, -64],
    area: 2780400,
    translations: {
      de: 'Argentinien', es: 'Argentina', fr: 'Argentine', ja: 'アルゼンチン', it: 'Argentina', br: 'Argentina', pt: 'Argentina', nl: 'Argentinië', hr: 'Argentina', fa: 'آرژانتین',
    },
    flag: 'https://restcountries.eu/data/arg.svg',
  }, {
    name: 'Armenia',
    id: 'ARM',
    capital: 'Yerevan',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 2994400,
    latlng: [40, 45],
    area: 29743,
    translations: {
      de: 'Armenien', es: 'Armenia', fr: 'Arménie', ja: 'アルメニア', it: 'Armenia', br: 'Armênia', pt: 'Arménia', nl: 'Armenië', hr: 'Armenija', fa: 'ارمنستان',
    },
    flag: 'https://restcountries.eu/data/arm.svg',
  }, {
    name: 'Australia',
    id: 'AUS',
    capital: 'Canberra',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 24117360,
    latlng: [-27, 133],
    area: 7692024,
    translations: {
      de: 'Australien', es: 'Australia', fr: 'Australie', ja: 'オーストラリア', it: 'Australia', br: 'Austrália', pt: 'Austrália', nl: 'Australië', hr: 'Australija', fa: 'استرالیا',
    },
    flag: 'https://restcountries.eu/data/aus.svg',
  }, {
    name: 'Austria',
    id: 'AUT',
    capital: 'Vienna',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 8725931,
    latlng: [47.33333333, 13.33333333],
    area: 83871,
    translations: {
      de: 'Österreich', es: 'Austria', fr: 'Autriche', ja: 'オーストリア', it: 'Austria', br: 'áustria', pt: 'áustria', nl: 'Oostenrijk', hr: 'Austrija', fa: 'اتریش',
    },
    flag: 'https://restcountries.eu/data/aut.svg',
  }, {
    name: 'Azerbaijan',
    id: 'AZE',
    capital: 'Baku',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 9730500,
    latlng: [40.5, 47.5],
    area: 86600,
    translations: {
      de: 'Aserbaidschan', es: 'Azerbaiyán', fr: 'Azerbaïdjan', ja: 'アゼルバイジャン', it: 'Azerbaijan', br: 'Azerbaijão', pt: 'Azerbaijão', nl: 'Azerbeidzjan', hr: 'Azerbajdžan', fa: 'آذربایجان',
    },
    flag: 'https://restcountries.eu/data/aze.svg',
  }, {
    name: 'Bahamas',
    id: 'BHS',
    capital: 'Nassau',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 378040,
    latlng: [24.25, -76],
    area: 13943,
    translations: {
      de: 'Bahamas', es: 'Bahamas', fr: 'Bahamas', ja: 'バハマ', it: 'Bahamas', br: 'Bahamas', pt: 'Baamas', nl: 'Bahama’s', hr: 'Bahami', fa: 'باهاما',
    },
    flag: 'https://restcountries.eu/data/bhs.svg',
  }, {
    name: 'Bahrain',
    id: 'BHR',
    capital: 'Manama',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 1404900,
    latlng: [26, 50.55],
    area: 765,
    translations: {
      de: 'Bahrain', es: 'Bahrein', fr: 'Bahreïn', ja: 'バーレーン', it: 'Bahrein', br: 'Bahrein', pt: 'Barém', nl: 'Bahrein', hr: 'Bahrein', fa: 'بحرین',
    },
    flag: 'https://restcountries.eu/data/bhr.svg',
  }, {
    name: 'Bangladesh',
    id: 'BGD',
    capital: 'Dhaka',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 161006790,
    latlng: [24, 90],
    area: 147570,
    translations: {
      de: 'Bangladesch', es: 'Bangladesh', fr: 'Bangladesh', ja: 'バングラデシュ', it: 'Bangladesh', br: 'Bangladesh', pt: 'Bangladeche', nl: 'Bangladesh', hr: 'Bangladeš', fa: 'بنگلادش',
    },
    flag: 'https://restcountries.eu/data/bgd.svg',
  }, {
    name: 'Barbados',
    id: 'BRB',
    capital: 'Bridgetown',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 285000,
    latlng: [13.16666666, -59.53333333],
    area: 430,
    translations: {
      de: 'Barbados', es: 'Barbados', fr: 'Barbade', ja: 'バルバドス', it: 'Barbados', br: 'Barbados', pt: 'Barbados', nl: 'Barbados', hr: 'Barbados', fa: 'باربادوس',
    },
    flag: 'https://restcountries.eu/data/brb.svg',
  }, {
    name: 'Belarus',
    id: 'BLR',
    capital: 'Minsk',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 9498700,
    latlng: [53, 28],
    area: 207600,
    translations: {
      de: 'Weißrussland', es: 'Bielorrusia', fr: 'Biélorussie', ja: 'ベラルーシ', it: 'Bielorussia', br: 'Bielorrússia', pt: 'Bielorrússia', nl: 'Wit-Rusland', hr: 'Bjelorusija', fa: 'بلاروس',
    },
    flag: 'https://restcountries.eu/data/blr.svg',
  }, {
    name: 'Belgium',
    id: 'BEL',
    capital: 'Brussels',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 11319511,
    latlng: [50.83333333, 4],
    area: 30528,
    translations: {
      de: 'Belgien', es: 'Bélgica', fr: 'Belgique', ja: 'ベルギー', it: 'Belgio', br: 'Bélgica', pt: 'Bélgica', nl: 'België', hr: 'Belgija', fa: 'بلژیک',
    },
    flag: 'https://restcountries.eu/data/bel.svg',
  }, {
    name: 'Belize',
    id: 'BLZ',
    capital: 'Belmopan',
    region: 'Americas',
    subregion: 'Central America',
    population: 370300,
    latlng: [17.25, -88.75],
    area: 22966,
    translations: {
      de: 'Belize', es: 'Belice', fr: 'Belize', ja: 'ベリーズ', it: 'Belize', br: 'Belize', pt: 'Belize', nl: 'Belize', hr: 'Belize', fa: 'بلیز',
    },
    flag: 'https://restcountries.eu/data/blz.svg',
  }, {
    name: 'Benin',
    id: 'BEN',
    capital: 'Porto-Novo',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 10653654,
    latlng: [9.5, 2.25],
    area: 112622,
    translations: {
      de: 'Benin', es: 'Benín', fr: 'Bénin', ja: 'ベナン', it: 'Benin', br: 'Benin', pt: 'Benim', nl: 'Benin', hr: 'Benin', fa: 'بنین',
    },
    flag: 'https://restcountries.eu/data/ben.svg',
  }, {
    name: 'Bhutan',
    id: 'BTN',
    capital: 'Thimphu',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 775620,
    latlng: [27.5, 90.5],
    area: 38394,
    translations: {
      de: 'Bhutan', es: 'Bután', fr: 'Bhoutan', ja: 'ブータン', it: 'Bhutan', br: 'Butão', pt: 'Butão', nl: 'Bhutan', hr: 'Butan', fa: 'بوتان',
    },
    flag: 'https://restcountries.eu/data/btn.svg',
  }, {
    name: 'Bolivia (Plurinational State of)',
    id: 'BOL',
    capital: 'Sucre',
    region: 'Americas',
    subregion: 'South America',
    population: 10985059,
    latlng: [-17, -65],
    area: 1098581,
    translations: {
      de: 'Bolivien', es: 'Bolivia', fr: 'Bolivie', ja: 'ボリビア多民族国', it: 'Bolivia', br: 'Bolívia', pt: 'Bolívia', nl: 'Bolivia', hr: 'Bolivija', fa: 'بولیوی',
    },
    flag: 'https://restcountries.eu/data/bol.svg',
  }, {
    name: 'Bosnia and Herzegovina',
    id: 'BIH',
    capital: 'Sarajevo',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 3531159,
    latlng: [44, 18],
    area: 51209,
    translations: {
      de: 'Bosnien und Herzegowina', es: 'Bosnia y Herzegovina', fr: 'Bosnie-Herzégovine', ja: 'ボスニア・ヘルツェゴビナ', it: 'Bosnia ed Erzegovina', br: 'Bósnia e Herzegovina', pt: 'Bósnia e Herzegovina', nl: 'Bosnië en Herzegovina', hr: 'Bosna i Hercegovina', fa: 'بوسنی و هرزگوین',
    },
    flag: 'https://restcountries.eu/data/bih.svg',
  }, {
    name: 'Botswana',
    id: 'BWA',
    capital: 'Gaborone',
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 2141206,
    latlng: [-22, 24],
    area: 582000,
    translations: {
      de: 'Botswana', es: 'Botswana', fr: 'Botswana', ja: 'ボツワナ', it: 'Botswana', br: 'Botsuana', pt: 'Botsuana', nl: 'Botswana', hr: 'Bocvana', fa: 'بوتسوانا',
    },
    flag: 'https://restcountries.eu/data/bwa.svg',
  }, {
    name: 'Brazil',
    id: 'BRA',
    capital: 'Brasília',
    region: 'Americas',
    subregion: 'South America',
    population: 206135893,
    latlng: [-10, -55],
    area: 8515767,
    translations: {
      de: 'Brasilien', es: 'Brasil', fr: 'Brésil', ja: 'ブラジル', it: 'Brasile', br: 'Brasil', pt: 'Brasil', nl: 'Brazilië', hr: 'Brazil', fa: 'برزیل',
    },
    flag: 'https://restcountries.eu/data/bra.svg',
  }, {
    name: 'Brunei Darussalam',
    id: 'BRN',
    capital: 'Bandar Seri Begawan',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 411900,
    latlng: [4.5, 114.66666666],
    area: 5765,
    translations: {
      de: 'Brunei', es: 'Brunei', fr: 'Brunei', ja: 'ブルネイ・ダルサラーム', it: 'Brunei', br: 'Brunei', pt: 'Brunei', nl: 'Brunei', hr: 'Brunej', fa: 'برونئی',
    },
    flag: 'https://restcountries.eu/data/brn.svg',
  }, {
    name: 'Bulgaria',
    id: 'BGR',
    capital: 'Sofia',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 7153784,
    latlng: [43, 25],
    area: 110879,
    translations: {
      de: 'Bulgarien', es: 'Bulgaria', fr: 'Bulgarie', ja: 'ブルガリア', it: 'Bulgaria', br: 'Bulgária', pt: 'Bulgária', nl: 'Bulgarije', hr: 'Bugarska', fa: 'بلغارستان',
    },
    flag: 'https://restcountries.eu/data/bgr.svg',
  }, {
    name: 'Burkina Faso',
    id: 'BFA',
    capital: 'Ouagadougou',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 19034397,
    latlng: [13, -2],
    area: 272967,
    translations: {
      de: 'Burkina Faso', es: 'Burkina Faso', fr: 'Burkina Faso', ja: 'ブルキナファソ', it: 'Burkina Faso', br: 'Burkina Faso', pt: 'Burquina Faso', nl: 'Burkina Faso', hr: 'Burkina Faso', fa: 'بورکینافاسو',
    },
    flag: 'https://restcountries.eu/data/bfa.svg',
  }, {
    name: 'Burundi',
    id: 'BDI',
    capital: 'Bujumbura',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 10114505,
    latlng: [-3.5, 30],
    area: 27834,
    translations: {
      de: 'Burundi', es: 'Burundi', fr: 'Burundi', ja: 'ブルンジ', it: 'Burundi', br: 'Burundi', pt: 'Burúndi', nl: 'Burundi', hr: 'Burundi', fa: 'بوروندی',
    },
    flag: 'https://restcountries.eu/data/bdi.svg',
  }, {
    name: 'Cambodia',
    id: 'KHM',
    capital: 'Phnom Penh',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 15626444,
    latlng: [13, 105],
    area: 181035,
    translations: {
      de: 'Kambodscha', es: 'Camboya', fr: 'Cambodge', ja: 'カンボジア', it: 'Cambogia', br: 'Camboja', pt: 'Camboja', nl: 'Cambodja', hr: 'Kambodža', fa: 'کامبوج',
    },
    flag: 'https://restcountries.eu/data/khm.svg',
  }, {
    name: 'Cameroon',
    id: 'CMR',
    capital: 'Yaoundé',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 22709892,
    latlng: [6, 12],
    area: 475442,
    translations: {
      de: 'Kamerun', es: 'Camerún', fr: 'Cameroun', ja: 'カメルーン', it: 'Camerun', br: 'Camarões', pt: 'Camarões', nl: 'Kameroen', hr: 'Kamerun', fa: 'کامرون',
    },
    flag: 'https://restcountries.eu/data/cmr.svg',
  }, {
    name: 'Canada',
    id: 'CAN',
    capital: 'Ottawa',
    region: 'Americas',
    subregion: 'Northern America',
    population: 36155487,
    latlng: [60, -95],
    area: 9984670,
    translations: {
      de: 'Kanada', es: 'Canadá', fr: 'Canada', ja: 'カナダ', it: 'Canada', br: 'Canadá', pt: 'Canadá', nl: 'Canada', hr: 'Kanada', fa: 'کانادا',
    },
    flag: 'https://restcountries.eu/data/can.svg',
  }, {
    name: 'Cabo Verde',
    id: 'CPV',
    capital: 'Praia',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 531239,
    latlng: [16, -24],
    area: 4033,
    translations: {
      de: 'Kap Verde', es: 'Cabo Verde', fr: 'Cap Vert', ja: 'カーボベルデ', it: 'Capo Verde', br: 'Cabo Verde', pt: 'Cabo Verde', nl: 'Kaapverdië', hr: 'Zelenortska Republika', fa: 'کیپ ورد',
    },
    flag: 'https://restcountries.eu/data/cpv.svg',
  }, {
    name: 'Central African Republic',
    id: 'CAF',
    capital: 'Bangui',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 4998000,
    latlng: [7, 21],
    area: 622984,
    translations: {
      de: 'Zentralafrikanische Republik', es: 'República Centroafricana', fr: 'République centrafricaine', ja: '中央アフリカ共和国', it: 'Repubblica Centrafricana', br: 'República Centro-Africana', pt: 'República Centro-Africana', nl: 'Centraal-Afrikaanse Republiek', hr: 'Srednjoafrička Republika', fa: 'جمهوری آفریقای مرکزی',
    },
    flag: 'https://restcountries.eu/data/caf.svg',
  }, {
    name: 'Chad',
    id: 'TCD',
    capital: "N'Djamena",
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 14497000,
    latlng: [15, 19],
    area: 1284000,
    translations: {
      de: 'Tschad', es: 'Chad', fr: 'Tchad', ja: 'チャド', it: 'Ciad', br: 'Chade', pt: 'Chade', nl: 'Tsjaad', hr: 'Čad', fa: 'چاد',
    },
    flag: 'https://restcountries.eu/data/tcd.svg',
  }, {
    name: 'Chile',
    id: 'CHL',
    capital: 'Santiago',
    region: 'Americas',
    subregion: 'South America',
    population: 18191900,
    latlng: [-30, -71],
    area: 756102,
    translations: {
      de: 'Chile', es: 'Chile', fr: 'Chili', ja: 'チリ', it: 'Cile', br: 'Chile', pt: 'Chile', nl: 'Chili', hr: 'Čile', fa: 'شیلی',
    },
    flag: 'https://restcountries.eu/data/chl.svg',
  }, {
    name: 'China',
    id: 'CHN',
    capital: 'Beijing',
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 1377422166,
    latlng: [35, 105],
    area: 9640011,
    translations: {
      de: 'China', es: 'China', fr: 'Chine', ja: '中国', it: 'Cina', br: 'China', pt: 'China', nl: 'China', hr: 'Kina', fa: 'چین',
    },
    flag: 'https://restcountries.eu/data/chn.svg',
  }, {
    name: 'Colombia',
    id: 'COL',
    capital: 'Bogotá',
    region: 'Americas',
    subregion: 'South America',
    population: 48759958,
    latlng: [4, -72],
    area: 1141748,
    translations: {
      de: 'Kolumbien', es: 'Colombia', fr: 'Colombie', ja: 'コロンビア', it: 'Colombia', br: 'Colômbia', pt: 'Colômbia', nl: 'Colombia', hr: 'Kolumbija', fa: 'کلمبیا',
    },
    flag: 'https://restcountries.eu/data/col.svg',
  }, {
    name: 'Comoros',
    id: 'COM',
    capital: 'Moroni',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 806153,
    latlng: [-12.16666666, 44.25],
    area: 1862,
    translations: {
      de: 'Union der Komoren', es: 'Comoras', fr: 'Comores', ja: 'コモロ', it: 'Comore', br: 'Comores', pt: 'Comores', nl: 'Comoren', hr: 'Komori', fa: 'کومور',
    },
    flag: 'https://restcountries.eu/data/com.svg',
  }, {
    name: 'Congo',
    id: 'COG',
    capital: 'Brazzaville',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 4741000,
    latlng: [-1, 15],
    area: 342000,
    translations: {
      de: 'Kongo', es: 'Congo', fr: 'Congo', ja: 'コンゴ共和国', it: 'Congo', br: 'Congo', pt: 'Congo', nl: 'Congo [Republiek]', hr: 'Kongo', fa: 'کنگو',
    },
    flag: 'https://restcountries.eu/data/cog.svg',
  }, {
    name: 'Congo (Democratic Republic of the)',
    id: 'COD',
    capital: 'Kinshasa',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 85026000,
    latlng: [0, 25],
    area: 2344858,
    translations: {
      de: 'Kongo (Dem. Rep.)', es: 'Congo (Rep. Dem.)', fr: 'Congo (Rép. dém.)', ja: 'コンゴ民主共和国', it: 'Congo (Rep. Dem.)', br: 'RD Congo', pt: 'RD Congo', nl: 'Congo [DRC]', hr: 'Kongo, Demokratska Republika', fa: 'جمهوری کنگو',
    },
    flag: 'https://restcountries.eu/data/cod.svg',
  }, {
    name: 'Costa Rica',
    id: 'CRI',
    capital: 'San José',
    region: 'Americas',
    subregion: 'Central America',
    population: 4890379,
    latlng: [10, -84],
    area: 51100,
    translations: {
      de: 'Costa Rica', es: 'Costa Rica', fr: 'Costa Rica', ja: 'コスタリカ', it: 'Costa Rica', br: 'Costa Rica', pt: 'Costa Rica', nl: 'Costa Rica', hr: 'Kostarika', fa: 'کاستاریکا',
    },
    flag: 'https://restcountries.eu/data/cri.svg',
  }, {
    name: 'Croatia',
    id: 'HRV',
    capital: 'Zagreb',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 4190669,
    latlng: [45.16666666, 15.5],
    area: 56594,
    translations: {
      de: 'Kroatien', es: 'Croacia', fr: 'Croatie', ja: 'クロアチア', it: 'Croazia', br: 'Croácia', pt: 'Croácia', nl: 'Kroatië', hr: 'Hrvatska', fa: 'کرواسی',
    },
    flag: 'https://restcountries.eu/data/hrv.svg',
  }, {
    name: 'Cuba',
    id: 'CUB',
    capital: 'Havana',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 11239004,
    latlng: [21.5, -80],
    area: 109884,
    translations: {
      de: 'Kuba', es: 'Cuba', fr: 'Cuba', ja: 'キューバ', it: 'Cuba', br: 'Cuba', pt: 'Cuba', nl: 'Cuba', hr: 'Kuba', fa: 'کوبا',
    },
    flag: 'https://restcountries.eu/data/cub.svg',
  }, {
    name: 'Cyprus',
    id: 'CYP',
    capital: 'Nicosia',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 847000,
    latlng: [35, 33],
    area: 9251,
    translations: {
      de: 'Zypern', es: 'Chipre', fr: 'Chypre', ja: 'キプロス', it: 'Cipro', br: 'Chipre', pt: 'Chipre', nl: 'Cyprus', hr: 'Cipar', fa: 'قبرس',
    },
    flag: 'https://restcountries.eu/data/cyp.svg',
  }, {
    name: 'Czech Republic',
    id: 'CZE',
    capital: 'Prague',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 10558524,
    latlng: [49.75, 15.5],
    area: 78865,
    translations: {
      de: 'Tschechische Republik', es: 'República Checa', fr: 'République tchèque', ja: 'チェコ', it: 'Repubblica Ceca', br: 'República Tcheca', pt: 'República Checa', nl: 'Tsjechië', hr: 'Češka', fa: 'جمهوری چک',
    },
    flag: 'https://restcountries.eu/data/cze.svg',
  }, {
    name: 'Denmark',
    id: 'DNK',
    capital: 'Copenhagen',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 5717014,
    latlng: [56, 10],
    area: 43094,
    translations: {
      de: 'Dänemark', es: 'Dinamarca', fr: 'Danemark', ja: 'デンマーク', it: 'Danimarca', br: 'Dinamarca', pt: 'Dinamarca', nl: 'Denemarken', hr: 'Danska', fa: 'دانمارک',
    },
    flag: 'https://restcountries.eu/data/dnk.svg',
  }, {
    name: 'Djibouti',
    id: 'DJI',
    capital: 'Djibouti',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 900000,
    latlng: [11.5, 43],
    area: 23200,
    translations: {
      de: 'Dschibuti', es: 'Yibuti', fr: 'Djibouti', ja: 'ジブチ', it: 'Gibuti', br: 'Djibuti', pt: 'Djibuti', nl: 'Djibouti', hr: 'Džibuti', fa: 'جیبوتی',
    },
    flag: 'https://restcountries.eu/data/dji.svg',
  }, {
    name: 'Dominica',
    id: 'DMA',
    capital: 'Roseau',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 71293,
    latlng: [15.41666666, -61.33333333],
    area: 751,
    translations: {
      de: 'Dominica', es: 'Dominica', fr: 'Dominique', ja: 'ドミニカ国', it: 'Dominica', br: 'Dominica', pt: 'Dominica', nl: 'Dominica', hr: 'Dominika', fa: 'دومینیکا',
    },
    flag: 'https://restcountries.eu/data/dma.svg',
  }, {
    name: 'Dominican Republic',
    id: 'DOM',
    capital: 'Santo Domingo',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 10075045,
    latlng: [19, -70.66666666],
    area: 48671,
    translations: {
      de: 'Dominikanische Republik', es: 'República Dominicana', fr: 'République dominicaine', ja: 'ドミニカ共和国', it: 'Repubblica Dominicana', br: 'República Dominicana', pt: 'República Dominicana', nl: 'Dominicaanse Republiek', hr: 'Dominikanska Republika', fa: 'جمهوری دومینیکن',
    },
    flag: 'https://restcountries.eu/data/dom.svg',
  }, {
    name: 'Ecuador',
    id: 'ECU',
    capital: 'Quito',
    region: 'Americas',
    subregion: 'South America',
    population: 16545799,
    latlng: [-2, -77.5],
    area: 276841,
    translations: {
      de: 'Ecuador', es: 'Ecuador', fr: 'Équateur', ja: 'エクアドル', it: 'Ecuador', br: 'Equador', pt: 'Equador', nl: 'Ecuador', hr: 'Ekvador', fa: 'اکوادور',
    },
    flag: 'https://restcountries.eu/data/ecu.svg',
  }, {
    name: 'Egypt',
    id: 'EGY',
    capital: 'Cairo',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 91290000,
    latlng: [27, 30],
    area: 1002450,
    translations: {
      de: 'Ägypten', es: 'Egipto', fr: 'Égypte', ja: 'エジプト', it: 'Egitto', br: 'Egito', pt: 'Egipto', nl: 'Egypte', hr: 'Egipat', fa: 'مصر',
    },
    flag: 'https://restcountries.eu/data/egy.svg',
  }, {
    name: 'El Salvador',
    id: 'SLV',
    capital: 'San Salvador',
    region: 'Americas',
    subregion: 'Central America',
    population: 6520675,
    latlng: [13.83333333, -88.91666666],
    area: 21041,
    translations: {
      de: 'El Salvador', es: 'El Salvador', fr: 'Salvador', ja: 'エルサルバドル', it: 'El Salvador', br: 'El Salvador', pt: 'El Salvador', nl: 'El Salvador', hr: 'Salvador', fa: 'السالوادور',
    },
    flag: 'https://restcountries.eu/data/slv.svg',
  }, {
    name: 'Equatorial Guinea',
    id: 'GNQ',
    capital: 'Malabo',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 1222442,
    latlng: [2, 10],
    area: 28051,
    translations: {
      de: 'Äquatorial-Guinea', es: 'Guinea Ecuatorial', fr: 'Guinée-Équatoriale', ja: '赤道ギニア', it: 'Guinea Equatoriale', br: 'Guiné Equatorial', pt: 'Guiné Equatorial', nl: 'Equatoriaal-Guinea', hr: 'Ekvatorijalna Gvineja', fa: 'گینه استوایی',
    },
    flag: 'https://restcountries.eu/data/gnq.svg',
  }, {
    name: 'Eritrea',
    id: 'ERI',
    capital: 'Asmara',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 5352000,
    latlng: [15, 39],
    area: 117600,
    translations: {
      de: 'Eritrea', es: 'Eritrea', fr: 'Érythrée', ja: 'エリトリア', it: 'Eritrea', br: 'Eritreia', pt: 'Eritreia', nl: 'Eritrea', hr: 'Eritreja', fa: 'اریتره',
    },
    flag: 'https://restcountries.eu/data/eri.svg',
  }, {
    name: 'Estonia',
    id: 'EST',
    capital: 'Tallinn',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 1315944,
    latlng: [59, 26],
    area: 45227,
    translations: {
      de: 'Estland', es: 'Estonia', fr: 'Estonie', ja: 'エストニア', it: 'Estonia', br: 'Estônia', pt: 'Estónia', nl: 'Estland', hr: 'Estonija', fa: 'استونی',
    },
    flag: 'https://restcountries.eu/data/est.svg',
  }, {
    name: 'Ethiopia',
    id: 'ETH',
    capital: 'Addis Ababa',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 92206005,
    latlng: [8, 38],
    area: 1104300,
    translations: {
      de: 'Äthiopien', es: 'Etiopía', fr: 'Éthiopie', ja: 'エチオピア', it: 'Etiopia', br: 'Etiópia', pt: 'Etiópia', nl: 'Ethiopië', hr: 'Etiopija', fa: 'اتیوپی',
    },
    flag: 'https://restcountries.eu/data/eth.svg',
  }, {
    name: 'Fiji',
    id: 'FJI',
    capital: 'Suva',
    region: 'Oceania',
    subregion: 'Melanesia',
    population: 867000,
    latlng: [-18, 175],
    area: 18272,
    translations: {
      de: 'Fidschi', es: 'Fiyi', fr: 'Fidji', ja: 'フィジー', it: 'Figi', br: 'Fiji', pt: 'Fiji', nl: 'Fiji', hr: 'Fiđi', fa: 'فیجی',
    },
    flag: 'https://restcountries.eu/data/fji.svg',
  }, {
    name: 'Finland',
    id: 'FIN',
    capital: 'Helsinki',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 5491817,
    latlng: [64, 26],
    area: 338424,
    translations: {
      de: 'Finnland', es: 'Finlandia', fr: 'Finlande', ja: 'フィンランド', it: 'Finlandia', br: 'Finlândia', pt: 'Finlândia', nl: 'Finland', hr: 'Finska', fa: 'فنلاند',
    },
    flag: 'https://restcountries.eu/data/fin.svg',
  }, {
    name: 'France',
    id: 'FRA',
    capital: 'Paris',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 66710000,
    latlng: [46, 2],
    area: 640679,
    translations: {
      de: 'Frankreich', es: 'Francia', fr: 'France', ja: 'フランス', it: 'Francia', br: 'França', pt: 'França', nl: 'Frankrijk', hr: 'Francuska', fa: 'فرانسه',
    },
    flag: 'https://restcountries.eu/data/fra.svg',
  }, {
    name: 'Gabon',
    id: 'GAB',
    capital: 'Libreville',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 1802278,
    latlng: [-1, 11.75],
    area: 267668,
    translations: {
      de: 'Gabun', es: 'Gabón', fr: 'Gabon', ja: 'ガボン', it: 'Gabon', br: 'Gabão', pt: 'Gabão', nl: 'Gabon', hr: 'Gabon', fa: 'گابن',
    },
    flag: 'https://restcountries.eu/data/gab.svg',
  }, {
    name: 'Gambia',
    id: 'GMB',
    capital: 'Banjul',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 1882450,
    latlng: [13.46666666, -16.56666666],
    area: 11295,
    translations: {
      de: 'Gambia', es: 'Gambia', fr: 'Gambie', ja: 'ガンビア', it: 'Gambia', br: 'Gâmbia', pt: 'Gâmbia', nl: 'Gambia', hr: 'Gambija', fa: 'گامبیا',
    },
    flag: 'https://restcountries.eu/data/gmb.svg',
  }, {
    name: 'Georgia',
    id: 'GEO',
    capital: 'Tbilisi',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 3720400,
    latlng: [42, 43.5],
    area: 69700,
    translations: {
      de: 'Georgien', es: 'Georgia', fr: 'Géorgie', ja: 'グルジア', it: 'Georgia', br: 'Geórgia', pt: 'Geórgia', nl: 'Georgië', hr: 'Gruzija', fa: 'گرجستان',
    },
    flag: 'https://restcountries.eu/data/geo.svg',
  }, {
    name: 'Germany',
    id: 'DEU',
    capital: 'Berlin',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 81770900,
    latlng: [51, 9],
    area: 357114,
    translations: {
      de: 'Deutschland', es: 'Alemania', fr: 'Allemagne', ja: 'ドイツ', it: 'Germania', br: 'Alemanha', pt: 'Alemanha', nl: 'Duitsland', hr: 'Njemačka', fa: 'آلمان',
    },
    flag: 'https://restcountries.eu/data/deu.svg',
  }, {
    name: 'Ghana',
    id: 'GHA',
    capital: 'Accra',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 27670174,
    latlng: [8, -2],
    area: 238533,
    translations: {
      de: 'Ghana', es: 'Ghana', fr: 'Ghana', ja: 'ガーナ', it: 'Ghana', br: 'Gana', pt: 'Gana', nl: 'Ghana', hr: 'Gana', fa: 'غنا',
    },
    flag: 'https://restcountries.eu/data/gha.svg',
  }, {
    name: 'Greece',
    id: 'GRC',
    capital: 'Athens',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 10858018,
    latlng: [39, 22],
    area: 131990,
    translations: {
      de: 'Griechenland', es: 'Grecia', fr: 'Grèce', ja: 'ギリシャ', it: 'Grecia', br: 'Grécia', pt: 'Grécia', nl: 'Griekenland', hr: 'Grčka', fa: 'یونان',
    },
    flag: 'https://restcountries.eu/data/grc.svg',
  }, {
    name: 'Grenada',
    id: 'GRD',
    capital: "St. George's",
    region: 'Americas',
    subregion: 'Caribbean',
    population: 103328,
    latlng: [12.11666666, -61.66666666],
    area: 344,
    translations: {
      de: 'Grenada', es: 'Grenada', fr: 'Grenade', ja: 'グレナダ', it: 'Grenada', br: 'Granada', pt: 'Granada', nl: 'Grenada', hr: 'Grenada', fa: 'گرنادا',
    },
    flag: 'https://restcountries.eu/data/grd.svg',
  }, {
    name: 'Guatemala',
    id: 'GTM',
    capital: 'Guatemala City',
    region: 'Americas',
    subregion: 'Central America',
    population: 16176133,
    latlng: [15.5, -90.25],
    area: 108889,
    translations: {
      de: 'Guatemala', es: 'Guatemala', fr: 'Guatemala', ja: 'グアテマラ', it: 'Guatemala', br: 'Guatemala', pt: 'Guatemala', nl: 'Guatemala', hr: 'Gvatemala', fa: 'گواتمالا',
    },
    flag: 'https://restcountries.eu/data/gtm.svg',
  }, {
    name: 'Guinea',
    id: 'GIN',
    capital: 'Conakry',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 12947000,
    latlng: [11, -10],
    area: 245857,
    translations: {
      de: 'Guinea', es: 'Guinea', fr: 'Guinée', ja: 'ギニア', it: 'Guinea', br: 'Guiné', pt: 'Guiné', nl: 'Guinee', hr: 'Gvineja', fa: 'گینه',
    },
    flag: 'https://restcountries.eu/data/gin.svg',
  }, {
    name: 'Guinea-Bissau',
    id: 'GNB',
    capital: 'Bissau',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 1547777,
    latlng: [12, -15],
    area: 36125,
    translations: {
      de: 'Guinea-Bissau', es: 'Guinea-Bisáu', fr: 'Guinée-Bissau', ja: 'ギニアビサウ', it: 'Guinea-Bissau', br: 'Guiné-Bissau', pt: 'Guiné-Bissau', nl: 'Guinee-Bissau', hr: 'Gvineja Bisau', fa: 'گینه بیسائو',
    },
    flag: 'https://restcountries.eu/data/gnb.svg',
  }, {
    name: 'Guyana',
    id: 'GUY',
    capital: 'Georgetown',
    region: 'Americas',
    subregion: 'South America',
    population: 746900,
    latlng: [5, -59],
    area: 214969,
    translations: {
      de: 'Guyana', es: 'Guyana', fr: 'Guyane', ja: 'ガイアナ', it: 'Guyana', br: 'Guiana', pt: 'Guiana', nl: 'Guyana', hr: 'Gvajana', fa: 'گویان',
    },
    flag: 'https://restcountries.eu/data/guy.svg',
  }, {
    name: 'Haiti',
    id: 'HTI',
    capital: 'Port-au-Prince',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 11078033,
    latlng: [19, -72.41666666],
    area: 27750,
    translations: {
      de: 'Haiti', es: 'Haiti', fr: 'Haïti', ja: 'ハイチ', it: 'Haiti', br: 'Haiti', pt: 'Haiti', nl: 'Haïti', hr: 'Haiti', fa: 'هائیتی',
    },
    flag: 'https://restcountries.eu/data/hti.svg',
  }, {
    name: 'Holy See',
    id: 'VAT',
    capital: 'Rome',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 451,
    latlng: [41.9, 12.45],
    area: 0.44,
    translations: {
      de: 'Heiliger Stuhl', es: 'Santa Sede', fr: 'voir Saint', ja: '聖座', it: 'Santa Sede', br: 'Vaticano', pt: 'Vaticano', nl: 'Heilige Stoel', hr: 'Sveta Stolica', fa: 'سریر مقدس',
    },
    flag: 'https://restcountries.eu/data/vat.svg',
  }, {
    name: 'Honduras',
    id: 'HND',
    capital: 'Tegucigalpa',
    region: 'Americas',
    subregion: 'Central America',
    population: 8576532,
    latlng: [15, -86.5],
    area: 112492,
    translations: {
      de: 'Honduras', es: 'Honduras', fr: 'Honduras', ja: 'ホンジュラス', it: 'Honduras', br: 'Honduras', pt: 'Honduras', nl: 'Honduras', hr: 'Honduras', fa: 'هندوراس',
    },
    flag: 'https://restcountries.eu/data/hnd.svg',
  }, {
    name: 'Hungary',
    id: 'HUN',
    capital: 'Budapest',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 9823000,
    latlng: [47, 20],
    area: 93028,
    translations: {
      de: 'Ungarn', es: 'Hungría', fr: 'Hongrie', ja: 'ハンガリー', it: 'Ungheria', br: 'Hungria', pt: 'Hungria', nl: 'Hongarije', hr: 'Mađarska', fa: 'مجارستان',
    },
    flag: 'https://restcountries.eu/data/hun.svg',
  }, {
    name: 'Iceland',
    id: 'ISL',
    capital: 'Reykjavík',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 334300,
    latlng: [65, -18],
    area: 103000,
    translations: {
      de: 'Island', es: 'Islandia', fr: 'Islande', ja: 'アイスランド', it: 'Islanda', br: 'Islândia', pt: 'Islândia', nl: 'IJsland', hr: 'Island', fa: 'ایسلند',
    },
    flag: 'https://restcountries.eu/data/isl.svg',
  }, {
    name: 'India',
    id: 'IND',
    capital: 'New Delhi',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 1295210000,
    latlng: [20, 77],
    area: 3287590,
    translations: {
      de: 'Indien', es: 'India', fr: 'Inde', ja: 'インド', it: 'India', br: 'Índia', pt: 'Índia', nl: 'India', hr: 'Indija', fa: 'هند',
    },
    flag: 'https://restcountries.eu/data/ind.svg',
  }, {
    name: 'Indonesia',
    id: 'IDN',
    capital: 'Jakarta',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 258705000,
    latlng: [-5, 120],
    area: 1904569,
    translations: {
      de: 'Indonesien', es: 'Indonesia', fr: 'Indonésie', ja: 'インドネシア', it: 'Indonesia', br: 'Indonésia', pt: 'Indonésia', nl: 'Indonesië', hr: 'Indonezija', fa: 'اندونزی',
    },
    flag: 'https://restcountries.eu/data/idn.svg',
  }, {
    name: "Côte d'Ivoire",
    id: 'CIV',
    capital: 'Yamoussoukro',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 22671331,
    latlng: [8, -5],
    area: 322463,
    translations: {
      de: 'Elfenbeinküste', es: 'Costa de Marfil', fr: "Côte d'Ivoire", ja: 'コートジボワール', it: "Costa D'Avorio", br: 'Costa do Marfim', pt: 'Costa do Marfim', nl: 'Ivoorkust', hr: 'Obala Bjelokosti', fa: 'ساحل عاج',
    },
    flag: 'https://restcountries.eu/data/civ.svg',
  }, {
    name: 'Iran (Islamic Republic of)',
    id: 'IRN',
    capital: 'Tehran',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 79369900,
    latlng: [32, 53],
    area: 1648195,
    translations: {
      de: 'Iran', es: 'Iran', fr: 'Iran', ja: 'イラン・イスラム共和国', it: null, br: 'Irã', pt: 'Irão', nl: 'Iran', hr: 'Iran', fa: 'ایران',
    },
    flag: 'https://restcountries.eu/data/irn.svg',
  }, {
    name: 'Iraq',
    id: 'IRQ',
    capital: 'Baghdad',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 37883543,
    latlng: [33, 44],
    area: 438317,
    translations: {
      de: 'Irak', es: 'Irak', fr: 'Irak', ja: 'イラク', it: 'Iraq', br: 'Iraque', pt: 'Iraque', nl: 'Irak', hr: 'Irak', fa: 'عراق',
    },
    flag: 'https://restcountries.eu/data/irq.svg',
  }, {
    name: 'Ireland',
    id: 'IRL',
    capital: 'Dublin',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 6378000,
    latlng: [53, -8],
    area: 70273,
    translations: {
      de: 'Irland', es: 'Irlanda', fr: 'Irlande', ja: 'アイルランド', it: 'Irlanda', br: 'Irlanda', pt: 'Irlanda', nl: 'Ierland', hr: 'Irska', fa: 'ایرلند',
    },
    flag: 'https://restcountries.eu/data/irl.svg',
  }, {
    name: 'Israel',
    id: 'ISR',
    capital: 'Jerusalem',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 8527400,
    latlng: [31.5, 34.75],
    area: 20770,
    translations: {
      de: 'Israel', es: 'Israel', fr: 'Israël', ja: 'イスラエル', it: 'Israele', br: 'Israel', pt: 'Israel', nl: 'Israël', hr: 'Izrael', fa: 'اسرائیل',
    },
    flag: 'https://restcountries.eu/data/isr.svg',
  }, {
    name: 'Italy',
    id: 'ITA',
    capital: 'Rome',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 60665551,
    latlng: [42.83333333, 12.83333333],
    area: 301336,
    translations: {
      de: 'Italien', es: 'Italia', fr: 'Italie', ja: 'イタリア', it: 'Italia', br: 'Itália', pt: 'Itália', nl: 'Italië', hr: 'Italija', fa: 'ایتالیا',
    },
    flag: 'https://restcountries.eu/data/ita.svg',
  }, {
    name: 'Jamaica',
    id: 'JAM',
    capital: 'Kingston',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 2723246,
    latlng: [18.25, -77.5],
    area: 10991,
    translations: {
      de: 'Jamaika', es: 'Jamaica', fr: 'Jamaïque', ja: 'ジャマイカ', it: 'Giamaica', br: 'Jamaica', pt: 'Jamaica', nl: 'Jamaica', hr: 'Jamajka', fa: 'جامائیکا',
    },
    flag: 'https://restcountries.eu/data/jam.svg',
  }, {
    name: 'Japan',
    id: 'JPN',
    capital: 'Tokyo',
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 126960000,
    latlng: [36, 138],
    area: 377930,
    translations: {
      de: 'Japan', es: 'Japón', fr: 'Japon', ja: '日本', it: 'Giappone', br: 'Japão', pt: 'Japão', nl: 'Japan', hr: 'Japan', fa: 'ژاپن',
    },
    flag: 'https://restcountries.eu/data/jpn.svg',
  }, {
    name: 'Jordan',
    id: 'JOR',
    capital: 'Amman',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 9531712,
    latlng: [31, 36],
    area: 89342,
    translations: {
      de: 'Jordanien', es: 'Jordania', fr: 'Jordanie', ja: 'ヨルダン', it: 'Giordania', br: 'Jordânia', pt: 'Jordânia', nl: 'Jordanië', hr: 'Jordan', fa: 'اردن',
    },
    flag: 'https://restcountries.eu/data/jor.svg',
  }, {
    name: 'Kazakhstan',
    id: 'KAZ',
    capital: 'Astana',
    region: 'Asia',
    subregion: 'Central Asia',
    population: 17753200,
    latlng: [48, 68],
    area: 2724900,
    translations: {
      de: 'Kasachstan', es: 'Kazajistán', fr: 'Kazakhstan', ja: 'カザフスタン', it: 'Kazakistan', br: 'Cazaquistão', pt: 'Cazaquistão', nl: 'Kazachstan', hr: 'Kazahstan', fa: 'قزاقستان',
    },
    flag: 'https://restcountries.eu/data/kaz.svg',
  }, {
    name: 'Kenya',
    id: 'KEN',
    capital: 'Nairobi',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 47251000,
    latlng: [1, 38],
    area: 580367,
    translations: {
      de: 'Kenia', es: 'Kenia', fr: 'Kenya', ja: 'ケニア', it: 'Kenya', br: 'Quênia', pt: 'Quénia', nl: 'Kenia', hr: 'Kenija', fa: 'کنیا',
    },
    flag: 'https://restcountries.eu/data/ken.svg',
  }, {
    name: 'Kiribati',
    id: 'KIR',
    capital: 'South Tarawa',
    region: 'Oceania',
    subregion: 'Micronesia',
    population: 113400,
    latlng: [1.41666666, 173],
    area: 811,
    translations: {
      de: 'Kiribati', es: 'Kiribati', fr: 'Kiribati', ja: 'キリバス', it: 'Kiribati', br: 'Kiribati', pt: 'Quiribáti', nl: 'Kiribati', hr: 'Kiribati', fa: 'کیریباتی',
    },
    flag: 'https://restcountries.eu/data/kir.svg',
  }, {
    name: 'Kuwait',
    id: 'KWT',
    capital: 'Kuwait City',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 4183658,
    latlng: [29.5, 45.75],
    area: 17818,
    translations: {
      de: 'Kuwait', es: 'Kuwait', fr: 'Koweït', ja: 'クウェート', it: 'Kuwait', br: 'Kuwait', pt: 'Kuwait', nl: 'Koeweit', hr: 'Kuvajt', fa: 'کویت',
    },
    flag: 'https://restcountries.eu/data/kwt.svg',
  }, {
    name: 'Kyrgyzstan',
    id: 'KGZ',
    capital: 'Bishkek',
    region: 'Asia',
    subregion: 'Central Asia',
    population: 6047800,
    latlng: [41, 75],
    area: 199951,
    translations: {
      de: 'Kirgisistan', es: 'Kirguizistán', fr: 'Kirghizistan', ja: 'キルギス', it: 'Kirghizistan', br: 'Quirguistão', pt: 'Quirguizistão', nl: 'Kirgizië', hr: 'Kirgistan', fa: 'قرقیزستان',
    },
    flag: 'https://restcountries.eu/data/kgz.svg',
  }, {
    name: "Lao People's Democratic Republic",
    id: 'LAO',
    capital: 'Vientiane',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 6492400,
    latlng: [18, 105],
    area: 236800,
    translations: {
      de: 'Laos', es: 'Laos', fr: 'Laos', ja: 'ラオス人民民主共和国', it: 'Laos', br: 'Laos', pt: 'Laos', nl: 'Laos', hr: 'Laos', fa: 'لائوس',
    },
    flag: 'https://restcountries.eu/data/lao.svg',
  }, {
    name: 'Latvia',
    id: 'LVA',
    capital: 'Riga',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 1961600,
    latlng: [57, 25],
    area: 64559,
    translations: {
      de: 'Lettland', es: 'Letonia', fr: 'Lettonie', ja: 'ラトビア', it: 'Lettonia', br: 'Letônia', pt: 'Letónia', nl: 'Letland', hr: 'Latvija', fa: 'لتونی',
    },
    flag: 'https://restcountries.eu/data/lva.svg',
  }, {
    name: 'Lebanon',
    id: 'LBN',
    capital: 'Beirut',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 5988000,
    latlng: [33.83333333, 35.83333333],
    area: 10452,
    translations: {
      de: 'Libanon', es: 'Líbano', fr: 'Liban', ja: 'レバノン', it: 'Libano', br: 'Líbano', pt: 'Líbano', nl: 'Libanon', hr: 'Libanon', fa: 'لبنان',
    },
    flag: 'https://restcountries.eu/data/lbn.svg',
  }, {
    name: 'Lesotho',
    id: 'LSO',
    capital: 'Maseru',
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 1894194,
    latlng: [-29.5, 28.5],
    area: 30355,
    translations: {
      de: 'Lesotho', es: 'Lesotho', fr: 'Lesotho', ja: 'レソト', it: 'Lesotho', br: 'Lesoto', pt: 'Lesoto', nl: 'Lesotho', hr: 'Lesoto', fa: 'لسوتو',
    },
    flag: 'https://restcountries.eu/data/lso.svg',
  }, {
    name: 'Liberia',
    id: 'LBR',
    capital: 'Monrovia',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 4615000,
    latlng: [6.5, -9.5],
    area: 111369,
    translations: {
      de: 'Liberia', es: 'Liberia', fr: 'Liberia', ja: 'リベリア', it: 'Liberia', br: 'Libéria', pt: 'Libéria', nl: 'Liberia', hr: 'Liberija', fa: 'لیبریا',
    },
    flag: 'https://restcountries.eu/data/lbr.svg',
  }, {
    name: 'Libya',
    id: 'LBY',
    capital: 'Tripoli',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 6385000,
    latlng: [25, 17],
    area: 1759540,
    translations: {
      de: 'Libyen', es: 'Libia', fr: 'Libye', ja: 'リビア', it: 'Libia', br: 'Líbia', pt: 'Líbia', nl: 'Libië', hr: 'Libija', fa: 'لیبی',
    },
    flag: 'https://restcountries.eu/data/lby.svg',
  }, {
    name: 'Liechtenstein',
    id: 'LIE',
    capital: 'Vaduz',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 37623,
    latlng: [47.26666666, 9.53333333],
    area: 160,
    translations: {
      de: 'Liechtenstein', es: 'Liechtenstein', fr: 'Liechtenstein', ja: 'リヒテンシュタイン', it: 'Liechtenstein', br: 'Liechtenstein', pt: 'Listenstaine', nl: 'Liechtenstein', hr: 'Lihtenštajn', fa: 'لیختن‌اشتاین',
    },
    flag: 'https://restcountries.eu/data/lie.svg',
  }, {
    name: 'Lithuania',
    id: 'LTU',
    capital: 'Vilnius',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 2872294,
    latlng: [56, 24],
    area: 65300,
    translations: {
      de: 'Litauen', es: 'Lituania', fr: 'Lituanie', ja: 'リトアニア', it: 'Lituania', br: 'Lituânia', pt: 'Lituânia', nl: 'Litouwen', hr: 'Litva', fa: 'لیتوانی',
    },
    flag: 'https://restcountries.eu/data/ltu.svg',
  }, {
    name: 'Luxembourg',
    id: 'LUX',
    capital: 'Luxembourg',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 576200,
    latlng: [49.75, 6.16666666],
    area: 2586,
    translations: {
      de: 'Luxemburg', es: 'Luxemburgo', fr: 'Luxembourg', ja: 'ルクセンブルク', it: 'Lussemburgo', br: 'Luxemburgo', pt: 'Luxemburgo', nl: 'Luxemburg', hr: 'Luksemburg', fa: 'لوکزامبورگ',
    },
    flag: 'https://restcountries.eu/data/lux.svg',
  }, {
    name: 'Macedonia (the former Yugoslav Republic of)',
    id: 'MKD',
    capital: 'Skopje',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 2058539,
    latlng: [41.83333333, 22],
    area: 25713,
    translations: {
      de: 'Mazedonien', es: 'Macedonia', fr: 'Macédoine', ja: 'マケドニア旧ユーゴスラビア共和国', it: 'Macedonia', br: 'Macedônia', pt: 'Macedónia', nl: 'Macedonië', hr: 'Makedonija', fa: '',
    },
    flag: 'https://restcountries.eu/data/mkd.svg',
  }, {
    name: 'Madagascar',
    id: 'MDG',
    capital: 'Antananarivo',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 22434363,
    latlng: [-20, 47],
    area: 587041,
    translations: {
      de: 'Madagaskar', es: 'Madagascar', fr: 'Madagascar', ja: 'マダガスカル', it: 'Madagascar', br: 'Madagascar', pt: 'Madagáscar', nl: 'Madagaskar', hr: 'Madagaskar', fa: 'ماداگاسکار',
    },
    flag: 'https://restcountries.eu/data/mdg.svg',
  }, {
    name: 'Malawi',
    id: 'MWI',
    capital: 'Lilongwe',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 16832910,
    latlng: [-13.5, 34],
    area: 118484,
    translations: {
      de: 'Malawi', es: 'Malawi', fr: 'Malawi', ja: 'マラウイ', it: 'Malawi', br: 'Malawi', pt: 'Malávi', nl: 'Malawi', hr: 'Malavi', fa: 'مالاوی',
    },
    flag: 'https://restcountries.eu/data/mwi.svg',
  }, {
    name: 'Malaysia',
    id: 'MYS',
    capital: 'Kuala Lumpur',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 31405416,
    latlng: [2.5, 112.5],
    area: 330803,
    translations: {
      de: 'Malaysia', es: 'Malasia', fr: 'Malaisie', ja: 'マレーシア', it: 'Malesia', br: 'Malásia', pt: 'Malásia', nl: 'Maleisië', hr: 'Malezija', fa: 'مالزی',
    },
    flag: 'https://restcountries.eu/data/mys.svg',
  }, {
    name: 'Maldives',
    id: 'MDV',
    capital: 'Malé',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 344023,
    latlng: [3.25, 73],
    area: 300,
    translations: {
      de: 'Malediven', es: 'Maldivas', fr: 'Maldives', ja: 'モルディブ', it: 'Maldive', br: 'Maldivas', pt: 'Maldivas', nl: 'Maldiven', hr: 'Maldivi', fa: 'مالدیو',
    },
    flag: 'https://restcountries.eu/data/mdv.svg',
  }, {
    name: 'Mali',
    id: 'MLI',
    capital: 'Bamako',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 18135000,
    latlng: [17, -4],
    area: 1240192,
    translations: {
      de: 'Mali', es: 'Mali', fr: 'Mali', ja: 'マリ', it: 'Mali', br: 'Mali', pt: 'Mali', nl: 'Mali', hr: 'Mali', fa: 'مالی',
    },
    flag: 'https://restcountries.eu/data/mli.svg',
  }, {
    name: 'Malta',
    id: 'MLT',
    capital: 'Valletta',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 425384,
    latlng: [35.83333333, 14.58333333],
    area: 316,
    translations: {
      de: 'Malta', es: 'Malta', fr: 'Malte', ja: 'マルタ', it: 'Malta', br: 'Malta', pt: 'Malta', nl: 'Malta', hr: 'Malta', fa: 'مالت',
    },
    flag: 'https://restcountries.eu/data/mlt.svg',
  }, {
    name: 'Marshall Islands',
    id: 'MHL',
    capital: 'Majuro',
    region: 'Oceania',
    subregion: 'Micronesia',
    population: 54880,
    latlng: [9, 168],
    area: 181,
    translations: {
      de: 'Marshallinseln', es: 'Islas Marshall', fr: 'Îles Marshall', ja: 'マーシャル諸島', it: 'Isole Marshall', br: 'Ilhas Marshall', pt: 'Ilhas Marshall', nl: 'Marshalleilanden', hr: 'Maršalovi Otoci', fa: 'جزایر مارشال',
    },
    flag: 'https://restcountries.eu/data/mhl.svg',
  }, {
    name: 'Mauritania',
    id: 'MRT',
    capital: 'Nouakchott',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 3718678,
    latlng: [20, -12],
    area: 1030700,
    translations: {
      de: 'Mauretanien', es: 'Mauritania', fr: 'Mauritanie', ja: 'モーリタニア', it: 'Mauritania', br: 'Mauritânia', pt: 'Mauritânia', nl: 'Mauritanië', hr: 'Mauritanija', fa: 'موریتانی',
    },
    flag: 'https://restcountries.eu/data/mrt.svg',
  }, {
    name: 'Mauritius',
    id: 'MUS',
    capital: 'Port Louis',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 1262879,
    latlng: [-20.28333333, 57.55],
    area: 2040,
    translations: {
      de: 'Mauritius', es: 'Mauricio', fr: 'Île Maurice', ja: 'モーリシャス', it: 'Mauritius', br: 'Maurício', pt: 'Maurícia', nl: 'Mauritius', hr: 'Mauricijus', fa: 'موریس',
    },
    flag: 'https://restcountries.eu/data/mus.svg',
  }, {
    name: 'Mexico',
    id: 'MEX',
    capital: 'Mexico City',
    region: 'Americas',
    subregion: 'Central America',
    population: 122273473,
    latlng: [23, -102],
    area: 1964375,
    translations: {
      de: 'Mexiko', es: 'México', fr: 'Mexique', ja: 'メキシコ', it: 'Messico', br: 'México', pt: 'México', nl: 'Mexico', hr: 'Meksiko', fa: 'مکزیک',
    },
    flag: 'https://restcountries.eu/data/mex.svg',
  }, {
    name: 'Micronesia (Federated States of)',
    id: 'FSM',
    capital: 'Palikir',
    region: 'Oceania',
    subregion: 'Micronesia',
    population: 102800,
    latlng: [6.91666666, 158.25],
    area: 702,
    translations: {
      de: 'Mikronesien', es: 'Micronesia', fr: 'Micronésie', ja: 'ミクロネシア連邦', it: 'Micronesia', br: 'Micronésia', pt: 'Micronésia', nl: 'Micronesië', hr: 'Mikronezija', fa: 'ایالات فدرال میکرونزی',
    },
    flag: 'https://restcountries.eu/data/fsm.svg',
  }, {
    name: 'Moldova (Republic of)',
    id: 'MDA',
    capital: 'Chișinău',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 3553100,
    latlng: [47, 29],
    area: 33846,
    translations: {
      de: 'Moldawie', es: 'Moldavia', fr: 'Moldavie', ja: 'モルドバ共和国', it: 'Moldavia', br: 'Moldávia', pt: 'Moldávia', nl: 'Moldavië', hr: 'Moldova', fa: 'مولداوی',
    },
    flag: 'https://restcountries.eu/data/mda.svg',
  }, {
    name: 'Monaco',
    id: 'MCO',
    capital: 'Monaco',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 38400,
    latlng: [43.73333333, 7.4],
    area: 2.02,
    translations: {
      de: 'Monaco', es: 'Mónaco', fr: 'Monaco', ja: 'モナコ', it: 'Principato di Monaco', br: 'Mônaco', pt: 'Mónaco', nl: 'Monaco', hr: 'Monako', fa: 'موناکو',
    },
    flag: 'https://restcountries.eu/data/mco.svg',
  }, {
    name: 'Mongolia',
    id: 'MNG',
    capital: 'Ulan Bator',
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 3093100,
    latlng: [46, 105],
    area: 1564110,
    translations: {
      de: 'Mongolei', es: 'Mongolia', fr: 'Mongolie', ja: 'モンゴル', it: 'Mongolia', br: 'Mongólia', pt: 'Mongólia', nl: 'Mongolië', hr: 'Mongolija', fa: 'مغولستان',
    },
    flag: 'https://restcountries.eu/data/mng.svg',
  }, {
    name: 'Montenegro',
    id: 'MNE',
    capital: 'Podgorica',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 621810,
    latlng: [42.5, 19.3],
    area: 13812,
    translations: {
      de: 'Montenegro', es: 'Montenegro', fr: 'Monténégro', ja: 'モンテネグロ', it: 'Montenegro', br: 'Montenegro', pt: 'Montenegro', nl: 'Montenegro', hr: 'Crna Gora', fa: 'مونته‌نگرو',
    },
    flag: 'https://restcountries.eu/data/mne.svg',
  }, {
    name: 'Morocco',
    id: 'MAR',
    capital: 'Rabat',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 33337529,
    latlng: [32, -5],
    area: 446550,
    translations: {
      de: 'Marokko', es: 'Marruecos', fr: 'Maroc', ja: 'モロッコ', it: 'Marocco', br: 'Marrocos', pt: 'Marrocos', nl: 'Marokko', hr: 'Maroko', fa: 'مراکش',
    },
    flag: 'https://restcountries.eu/data/mar.svg',
  }, {
    name: 'Mozambique',
    id: 'MOZ',
    capital: 'Maputo',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 26423700,
    latlng: [-18.25, 35],
    area: 801590,
    translations: {
      de: 'Mosambik', es: 'Mozambique', fr: 'Mozambique', ja: 'モザンビーク', it: 'Mozambico', br: 'Moçambique', pt: 'Moçambique', nl: 'Mozambique', hr: 'Mozambik', fa: 'موزامبیک',
    },
    flag: 'https://restcountries.eu/data/moz.svg',
  }, {
    name: 'Myanmar',
    id: 'MMR',
    capital: 'Naypyidaw',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 51419420,
    latlng: [22, 98],
    area: 676578,
    translations: {
      de: 'Myanmar', es: 'Myanmar', fr: 'Myanmar', ja: 'ミャンマー', it: 'Birmania', br: 'Myanmar', pt: 'Myanmar', nl: 'Myanmar', hr: 'Mijanmar', fa: 'میانمار',
    },
    flag: 'https://restcountries.eu/data/mmr.svg',
  }, {
    name: 'Namibia',
    id: 'NAM',
    capital: 'Windhoek',
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 2324388,
    latlng: [-22, 17],
    area: 825615,
    translations: {
      de: 'Namibia', es: 'Namibia', fr: 'Namibie', ja: 'ナミビア', it: 'Namibia', br: 'Namíbia', pt: 'Namíbia', nl: 'Namibië', hr: 'Namibija', fa: 'نامیبیا',
    },
    flag: 'https://restcountries.eu/data/nam.svg',
  }, {
    name: 'Nauru',
    id: 'NRU',
    capital: 'Yaren',
    region: 'Oceania',
    subregion: 'Micronesia',
    population: 10084,
    latlng: [-0.53333333, 166.91666666],
    area: 21,
    translations: {
      de: 'Nauru', es: 'Nauru', fr: 'Nauru', ja: 'ナウル', it: 'Nauru', br: 'Nauru', pt: 'Nauru', nl: 'Nauru', hr: 'Nauru', fa: 'نائورو',
    },
    flag: 'https://restcountries.eu/data/nru.svg',
  }, {
    name: 'Nepal',
    id: 'NPL',
    capital: 'Kathmandu',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 28431500,
    latlng: [28, 84],
    area: 147181,
    translations: {
      de: 'Népal', es: 'Nepal', fr: 'Népal', ja: 'ネパール', it: 'Nepal', br: 'Nepal', pt: 'Nepal', nl: 'Nepal', hr: 'Nepal', fa: 'نپال',
    },
    flag: 'https://restcountries.eu/data/npl.svg',
  }, {
    name: 'Netherlands',
    id: 'NLD',
    capital: 'Amsterdam',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 17019800,
    latlng: [52.5, 5.75],
    area: 41850,
    translations: {
      de: 'Niederlande', es: 'Países Bajos', fr: 'Pays-Bas', ja: 'オランダ', it: 'Paesi Bassi', br: 'Holanda', pt: 'Países Baixos', nl: 'Nederland', hr: 'Nizozemska', fa: 'پادشاهی هلند',
    },
    flag: 'https://restcountries.eu/data/nld.svg',
  }, {
    name: 'New Zealand',
    id: 'NZL',
    capital: 'Wellington',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 4697854,
    latlng: [-41, 174],
    area: 270467,
    translations: {
      de: 'Neuseeland', es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande', ja: 'ニュージーランド', it: 'Nuova Zelanda', br: 'Nova Zelândia', pt: 'Nova Zelândia', nl: 'Nieuw-Zeeland', hr: 'Novi Zeland', fa: 'نیوزیلند',
    },
    flag: 'https://restcountries.eu/data/nzl.svg',
  }, {
    name: 'Nicaragua',
    id: 'NIC',
    capital: 'Managua',
    region: 'Americas',
    subregion: 'Central America',
    population: 6262703,
    latlng: [13, -85],
    area: 130373,
    translations: {
      de: 'Nicaragua', es: 'Nicaragua', fr: 'Nicaragua', ja: 'ニカラグア', it: 'Nicaragua', br: 'Nicarágua', pt: 'Nicarágua', nl: 'Nicaragua', hr: 'Nikaragva', fa: 'نیکاراگوئه',
    },
    flag: 'https://restcountries.eu/data/nic.svg',
  }, {
    name: 'Niger',
    id: 'NER',
    capital: 'Niamey',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 20715000,
    latlng: [16, 8],
    area: 1267000,
    translations: {
      de: 'Niger', es: 'Níger', fr: 'Niger', ja: 'ニジェール', it: 'Niger', br: 'Níger', pt: 'Níger', nl: 'Niger', hr: 'Niger', fa: 'نیجر',
    },
    flag: 'https://restcountries.eu/data/ner.svg',
  }, {
    name: 'Nigeria',
    id: 'NGA',
    capital: 'Abuja',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 186988000,
    latlng: [10, 8],
    area: 923768,
    translations: {
      de: 'Nigeria', es: 'Nigeria', fr: 'Nigéria', ja: 'ナイジェリア', it: 'Nigeria', br: 'Nigéria', pt: 'Nigéria', nl: 'Nigeria', hr: 'Nigerija', fa: 'نیجریه',
    },
    flag: 'https://restcountries.eu/data/nga.svg',
  }, {
    name: "Korea (Democratic People's Republic of)",
    id: 'PRK',
    capital: 'Pyongyang',
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 25281000,
    latlng: [40, 127],
    area: 120538,
    translations: {
      de: 'Nordkorea', es: 'Corea del Norte', fr: 'Corée du Nord', ja: '朝鮮民主主義人民共和国', it: 'Corea del Nord', br: 'Coreia do Norte', pt: 'Coreia do Norte', nl: 'Noord-Korea', hr: 'Sjeverna Koreja', fa: 'کره جنوبی',
    },
    flag: 'https://restcountries.eu/data/prk.svg',
  }, {
    name: 'Norway',
    id: 'NOR',
    capital: 'Oslo',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 5223256,
    latlng: [62, 10],
    area: 323802,
    translations: {
      de: 'Norwegen', es: 'Noruega', fr: 'Norvège', ja: 'ノルウェー', it: 'Norvegia', br: 'Noruega', pt: 'Noruega', nl: 'Noorwegen', hr: 'Norveška', fa: 'نروژ',
    },
    flag: 'https://restcountries.eu/data/nor.svg',
  }, {
    name: 'Oman',
    id: 'OMN',
    capital: 'Muscat',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 4420133,
    latlng: [21, 57],
    area: 309500,
    translations: {
      de: 'Oman', es: 'Omán', fr: 'Oman', ja: 'オマーン', it: 'oman', br: 'Omã', pt: 'Omã', nl: 'Oman', hr: 'Oman', fa: 'عمان',
    },
    flag: 'https://restcountries.eu/data/omn.svg',
  }, {
    name: 'Pakistan',
    id: 'PAK',
    capital: 'Islamabad',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 194125062,
    latlng: [30, 70],
    area: 881912,
    translations: {
      de: 'Pakistan', es: 'Pakistán', fr: 'Pakistan', ja: 'パキスタン', it: 'Pakistan', br: 'Paquistão', pt: 'Paquistão', nl: 'Pakistan', hr: 'Pakistan', fa: 'پاکستان',
    },
    flag: 'https://restcountries.eu/data/pak.svg',
  }, {
    name: 'Palau',
    id: 'PLW',
    capital: 'Ngerulmud',
    region: 'Oceania',
    subregion: 'Micronesia',
    population: 17950,
    latlng: [7.5, 134.5],
    area: 459,
    translations: {
      de: 'Palau', es: 'Palau', fr: 'Palaos', ja: 'パラオ', it: 'Palau', br: 'Palau', pt: 'Palau', nl: 'Palau', hr: 'Palau', fa: 'پالائو',
    },
    flag: 'https://restcountries.eu/data/plw.svg',
  }, {
    name: 'Palestine, State of',
    id: 'PSE',
    capital: 'Ramallah',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 4682467,
    latlng: [31.9, 35.2],
    area: null,
    translations: {
      de: 'Palästina', es: 'Palestina', fr: 'Palestine', ja: 'パレスチナ', it: 'Palestina', br: 'Palestina', pt: 'Palestina', nl: 'Palestijnse gebieden', hr: 'Palestina', fa: 'فلسطین',
    },
    flag: 'https://restcountries.eu/data/pse.svg',
  }, {
    name: 'Panama',
    id: 'PAN',
    capital: 'Panama City',
    region: 'Americas',
    subregion: 'Central America',
    population: 3814672,
    latlng: [9, -80],
    area: 75417,
    translations: {
      de: 'Panama', es: 'Panamá', fr: 'Panama', ja: 'パナマ', it: 'Panama', br: 'Panamá', pt: 'Panamá', nl: 'Panama', hr: 'Panama', fa: 'پاناما',
    },
    flag: 'https://restcountries.eu/data/pan.svg',
  }, {
    name: 'Papua New Guinea',
    id: 'PNG',
    capital: 'Port Moresby',
    region: 'Oceania',
    subregion: 'Melanesia',
    population: 8083700,
    latlng: [-6, 147],
    area: 462840,
    translations: {
      de: 'Papua-Neuguinea', es: 'Papúa Nueva Guinea', fr: 'Papouasie-Nouvelle-Guinée', ja: 'パプアニューギニア', it: 'Papua Nuova Guinea', br: 'Papua Nova Guiné', pt: 'Papua Nova Guiné', nl: 'Papoea-Nieuw-Guinea', hr: 'Papua Nova Gvineja', fa: 'پاپوآ گینه نو',
    },
    flag: 'https://restcountries.eu/data/png.svg',
  }, {
    name: 'Paraguay',
    id: 'PRY',
    capital: 'Asunción',
    region: 'Americas',
    subregion: 'South America',
    population: 6854536,
    latlng: [-23, -58],
    area: 406752,
    translations: {
      de: 'Paraguay', es: 'Paraguay', fr: 'Paraguay', ja: 'パラグアイ', it: 'Paraguay', br: 'Paraguai', pt: 'Paraguai', nl: 'Paraguay', hr: 'Paragvaj', fa: 'پاراگوئه',
    },
    flag: 'https://restcountries.eu/data/pry.svg',
  }, {
    name: 'Peru',
    id: 'PER',
    capital: 'Lima',
    region: 'Americas',
    subregion: 'South America',
    population: 31488700,
    latlng: [-10, -76],
    area: 1285216,
    translations: {
      de: 'Peru', es: 'Perú', fr: 'Pérou', ja: 'ペルー', it: 'Perù', br: 'Peru', pt: 'Peru', nl: 'Peru', hr: 'Peru', fa: 'پرو',
    },
    flag: 'https://restcountries.eu/data/per.svg',
  }, {
    name: 'Philippines',
    id: 'PHL',
    capital: 'Manila',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 103279800,
    latlng: [13, 122],
    area: 342353,
    translations: {
      de: 'Philippinen', es: 'Filipinas', fr: 'Philippines', ja: 'フィリピン', it: 'Filippine', br: 'Filipinas', pt: 'Filipinas', nl: 'Filipijnen', hr: 'Filipini', fa: 'جزایر الندفیلیپین',
    },
    flag: 'https://restcountries.eu/data/phl.svg',
  }, {
    name: 'Poland',
    id: 'POL',
    capital: 'Warsaw',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 38437239,
    latlng: [52, 20],
    area: 312679,
    translations: {
      de: 'Polen', es: 'Polonia', fr: 'Pologne', ja: 'ポーランド', it: 'Polonia', br: 'Polônia', pt: 'Polónia', nl: 'Polen', hr: 'Poljska', fa: 'لهستان',
    },
    flag: 'https://restcountries.eu/data/pol.svg',
  }, {
    name: 'Portugal',
    id: 'PRT',
    capital: 'Lisbon',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 10374822,
    latlng: [39.5, -8],
    area: 92090,
    translations: {
      de: 'Portugal', es: 'Portugal', fr: 'Portugal', ja: 'ポルトガル', it: 'Portogallo', br: 'Portugal', pt: 'Portugal', nl: 'Portugal', hr: 'Portugal', fa: 'پرتغال',
    },
    flag: 'https://restcountries.eu/data/prt.svg',
  }, {
    name: 'Qatar',
    id: 'QAT',
    capital: 'Doha',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 2587564,
    latlng: [25.5, 51.25],
    area: 11586,
    translations: {
      de: 'Katar', es: 'Catar', fr: 'Qatar', ja: 'カタール', it: 'Qatar', br: 'Catar', pt: 'Catar', nl: 'Qatar', hr: 'Katar', fa: 'قطر',
    },
    flag: 'https://restcountries.eu/data/qat.svg',
  }, {
    name: 'Romania',
    id: 'ROU',
    capital: 'Bucharest',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 19861408,
    latlng: [46, 25],
    area: 238391,
    translations: {
      de: 'Rumänien', es: 'Rumania', fr: 'Roumanie', ja: 'ルーマニア', it: 'Romania', br: 'Romênia', pt: 'Roménia', nl: 'Roemenië', hr: 'Rumunjska', fa: 'رومانی',
    },
    flag: 'https://restcountries.eu/data/rou.svg',
  }, {
    name: 'Russian Federation',
    id: 'RUS',
    capital: 'Moscow',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 146599183,
    latlng: [60, 100],
    area: 17124442,
    translations: {
      de: 'Russland', es: 'Rusia', fr: 'Russie', ja: 'ロシア連邦', it: 'Russia', br: 'Rússia', pt: 'Rússia', nl: 'Rusland', hr: 'Rusija', fa: 'روسیه',
    },
    flag: 'https://restcountries.eu/data/rus.svg',
  }, {
    name: 'Rwanda',
    id: 'RWA',
    capital: 'Kigali',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 11553188,
    latlng: [-2, 30],
    area: 26338,
    translations: {
      de: 'Ruanda', es: 'Ruanda', fr: 'Rwanda', ja: 'ルワンダ', it: 'Ruanda', br: 'Ruanda', pt: 'Ruanda', nl: 'Rwanda', hr: 'Ruanda', fa: 'رواندا',
    },
    flag: 'https://restcountries.eu/data/rwa.svg',
  }, {
    name: 'Saint Kitts and Nevis',
    id: 'KNA',
    capital: 'Basseterre',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 46204,
    latlng: [17.33333333, -62.75],
    area: 261,
    translations: {
      de: 'St. Kitts und Nevis', es: 'San Cristóbal y Nieves', fr: 'Saint-Christophe-et-Niévès', ja: 'セントクリストファー・ネイビス', it: 'Saint Kitts e Nevis', br: 'São Cristóvão e Neves', pt: 'São Cristóvão e Neves', nl: 'Saint Kitts en Nevis', hr: 'Sveti Kristof i Nevis', fa: 'سنت کیتس و نویس',
    },
    flag: 'https://restcountries.eu/data/kna.svg',
  }, {
    name: 'Saint Lucia',
    id: 'LCA',
    capital: 'Castries',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 186000,
    latlng: [13.88333333, -60.96666666],
    area: 616,
    translations: {
      de: 'Saint Lucia', es: 'Santa Lucía', fr: 'Saint-Lucie', ja: 'セントルシア', it: 'Santa Lucia', br: 'Santa Lúcia', pt: 'Santa Lúcia', nl: 'Saint Lucia', hr: 'Sveta Lucija', fa: 'سنت لوسیا',
    },
    flag: 'https://restcountries.eu/data/lca.svg',
  }, {
    name: 'Saint Vincent and the Grenadines',
    id: 'VCT',
    capital: 'Kingstown',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 109991,
    latlng: [13.25, -61.2],
    area: 389,
    translations: {
      de: 'Saint Vincent und die Grenadinen', es: 'San Vicente y Granadinas', fr: 'Saint-Vincent-et-les-Grenadines', ja: 'セントビンセントおよびグレナディーン諸島', it: 'Saint Vincent e Grenadine', br: 'São Vicente e Granadinas', pt: 'São Vicente e Granadinas', nl: 'Saint Vincent en de Grenadines', hr: 'Sveti Vincent i Grenadini', fa: 'سنت وینسنت و گرنادین‌ها',
    },
    flag: 'https://restcountries.eu/data/vct.svg',
  }, {
    name: 'Samoa',
    id: 'WSM',
    capital: 'Apia',
    region: 'Oceania',
    subregion: 'Polynesia',
    population: 194899,
    latlng: [-13.58333333, -172.33333333],
    area: 2842,
    translations: {
      de: 'Samoa', es: 'Samoa', fr: 'Samoa', ja: 'サモア', it: 'Samoa', br: 'Samoa', pt: 'Samoa', nl: 'Samoa', hr: 'Samoa', fa: 'ساموآ',
    },
    flag: 'https://restcountries.eu/data/wsm.svg',
  }, {
    name: 'San Marino',
    id: 'SMR',
    capital: 'City of San Marino',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 33005,
    latlng: [43.76666666, 12.41666666],
    area: 61,
    translations: {
      de: 'San Marino', es: 'San Marino', fr: 'Saint-Marin', ja: 'サンマリノ', it: 'San Marino', br: 'San Marino', pt: 'São Marinho', nl: 'San Marino', hr: 'San Marino', fa: 'سان مارینو',
    },
    flag: 'https://restcountries.eu/data/smr.svg',
  }, {
    name: 'Sao Tome and Principe',
    id: 'STP',
    capital: 'São Tomé',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 187356,
    latlng: [1, 7],
    area: 964,
    translations: {
      de: 'São Tomé und Príncipe', es: 'Santo Tomé y Príncipe', fr: 'Sao Tomé-et-Principe', ja: 'サントメ・プリンシペ', it: 'São Tomé e Príncipe', br: 'São Tomé e Príncipe', pt: 'São Tomé e Príncipe', nl: 'Sao Tomé en Principe', hr: 'Sveti Toma i Princip', fa: 'کواترو دو فرویرو',
    },
    flag: 'https://restcountries.eu/data/stp.svg',
  }, {
    name: 'Saudi Arabia',
    id: 'SAU',
    capital: 'Riyadh',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 32248200,
    latlng: [25, 45],
    area: 2149690,
    translations: {
      de: 'Saudi-Arabien', es: 'Arabia Saudí', fr: 'Arabie Saoudite', ja: 'サウジアラビア', it: 'Arabia Saudita', br: 'Arábia Saudita', pt: 'Arábia Saudita', nl: 'Saoedi-Arabië', hr: 'Saudijska Arabija', fa: 'عربستان سعودی',
    },
    flag: 'https://restcountries.eu/data/sau.svg',
  }, {
    name: 'Senegal',
    id: 'SEN',
    capital: 'Dakar',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 14799859,
    latlng: [14, -14],
    area: 196722,
    translations: {
      de: 'Senegal', es: 'Senegal', fr: 'Sénégal', ja: 'セネガル', it: 'Senegal', br: 'Senegal', pt: 'Senegal', nl: 'Senegal', hr: 'Senegal', fa: 'سنگال',
    },
    flag: 'https://restcountries.eu/data/sen.svg',
  }, {
    name: 'Serbia',
    id: 'SRB',
    capital: 'Belgrade',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 7076372,
    latlng: [44, 21],
    area: 88361,
    translations: {
      de: 'Serbien', es: 'Serbia', fr: 'Serbie', ja: 'セルビア', it: 'Serbia', br: 'Sérvia', pt: 'Sérvia', nl: 'Servië', hr: 'Srbija', fa: 'صربستان',
    },
    flag: 'https://restcountries.eu/data/srb.svg',
  }, {
    name: 'Seychelles',
    id: 'SYC',
    capital: 'Victoria',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 91400,
    latlng: [-4.58333333, 55.66666666],
    area: 452,
    translations: {
      de: 'Seychellen', es: 'Seychelles', fr: 'Seychelles', ja: 'セーシェル', it: 'Seychelles', br: 'Seicheles', pt: 'Seicheles', nl: 'Seychellen', hr: 'Sejšeli', fa: 'سیشل',
    },
    flag: 'https://restcountries.eu/data/syc.svg',
  }, {
    name: 'Sierra Leone',
    id: 'SLE',
    capital: 'Freetown',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 7075641,
    latlng: [8.5, -11.5],
    area: 71740,
    translations: {
      de: 'Sierra Leone', es: 'Sierra Leone', fr: 'Sierra Leone', ja: 'シエラレオネ', it: 'Sierra Leone', br: 'Serra Leoa', pt: 'Serra Leoa', nl: 'Sierra Leone', hr: 'Sijera Leone', fa: 'سیرالئون',
    },
    flag: 'https://restcountries.eu/data/sle.svg',
  }, {
    name: 'Singapore',
    id: 'SGP',
    capital: 'Singapore',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 5535000,
    latlng: [1.36666666, 103.8],
    area: 710,
    translations: {
      de: 'Singapur', es: 'Singapur', fr: 'Singapour', ja: 'シンガポール', it: 'Singapore', br: 'Singapura', pt: 'Singapura', nl: 'Singapore', hr: 'Singapur', fa: 'سنگاپور',
    },
    flag: 'https://restcountries.eu/data/sgp.svg',
  }, {
    name: 'Slovakia',
    id: 'SVK',
    capital: 'Bratislava',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 5426252,
    latlng: [48.66666666, 19.5],
    area: 49037,
    translations: {
      de: 'Slowakei', es: 'República Eslovaca', fr: 'Slovaquie', ja: 'スロバキア', it: 'Slovacchia', br: 'Eslováquia', pt: 'Eslováquia', nl: 'Slowakije', hr: 'Slovačka', fa: 'اسلواکی',
    },
    flag: 'https://restcountries.eu/data/svk.svg',
  }, {
    name: 'Slovenia',
    id: 'SVN',
    capital: 'Ljubljana',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 2064188,
    latlng: [46.11666666, 14.81666666],
    area: 20273,
    translations: {
      de: 'Slowenien', es: 'Eslovenia', fr: 'Slovénie', ja: 'スロベニア', it: 'Slovenia', br: 'Eslovênia', pt: 'Eslovénia', nl: 'Slovenië', hr: 'Slovenija', fa: 'اسلوونی',
    },
    flag: 'https://restcountries.eu/data/svn.svg',
  }, {
    name: 'Solomon Islands',
    id: 'SLB',
    capital: 'Honiara',
    region: 'Oceania',
    subregion: 'Melanesia',
    population: 642000,
    latlng: [-8, 159],
    area: 28896,
    translations: {
      de: 'Salomonen', es: 'Islas Salomón', fr: 'Îles Salomon', ja: 'ソロモン諸島', it: 'Isole Salomone', br: 'Ilhas Salomão', pt: 'Ilhas Salomão', nl: 'Salomonseilanden', hr: 'Solomonski Otoci', fa: 'جزایر سلیمان',
    },
    flag: 'https://restcountries.eu/data/slb.svg',
  }, {
    name: 'Somalia',
    id: 'SOM',
    capital: 'Mogadishu',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 11079000,
    latlng: [10, 49],
    area: 637657,
    translations: {
      de: 'Somalia', es: 'Somalia', fr: 'Somalie', ja: 'ソマリア', it: 'Somalia', br: 'Somália', pt: 'Somália', nl: 'Somalië', hr: 'Somalija', fa: 'سومالی',
    },
    flag: 'https://restcountries.eu/data/som.svg',
  }, {
    name: 'South Africa',
    id: 'ZAF',
    capital: 'Pretoria',
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 55653654,
    latlng: [-29, 24],
    area: 1221037,
    translations: {
      de: 'Republik Südafrika', es: 'República de Sudáfrica', fr: 'Afrique du Sud', ja: '南アフリカ', it: 'Sud Africa', br: 'República Sul-Africana', pt: 'República Sul-Africana', nl: 'Zuid-Afrika', hr: 'Južnoafrička Republika', fa: 'آفریقای جنوبی',
    },
    flag: 'https://restcountries.eu/data/zaf.svg',
  }, {
    name: 'Korea (Republic of)',
    id: 'KOR',
    capital: 'Seoul',
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 50801405,
    latlng: [37, 127.5],
    area: 100210,
    translations: {
      de: 'Südkorea', es: 'Corea del Sur', fr: 'Corée du Sud', ja: '大韓民国', it: 'Corea del Sud', br: 'Coreia do Sul', pt: 'Coreia do Sul', nl: 'Zuid-Korea', hr: 'Južna Koreja', fa: 'کره شمالی',
    },
    flag: 'https://restcountries.eu/data/kor.svg',
  }, {
    name: 'South Sudan',
    id: 'SSD',
    capital: 'Juba',
    region: 'Africa',
    subregion: 'Middle Africa',
    population: 12131000,
    latlng: [7, 30],
    area: 619745,
    translations: {
      de: 'Südsudan', es: 'Sudán del Sur', fr: 'Soudan du Sud', ja: '南スーダン', it: 'Sudan del sud', br: 'Sudão do Sul', pt: 'Sudão do Sul', nl: 'Zuid-Soedan', hr: 'Južni Sudan', fa: 'سودان جنوبی',
    },
    flag: 'https://restcountries.eu/data/ssd.svg',
  }, {
    name: 'Spain',
    id: 'ESP',
    capital: 'Madrid',
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 46438422,
    latlng: [40, -4],
    area: 505992,
    translations: {
      de: 'Spanien', es: 'España', fr: 'Espagne', ja: 'スペイン', it: 'Spagna', br: 'Espanha', pt: 'Espanha', nl: 'Spanje', hr: 'Španjolska', fa: 'اسپانیا',
    },
    flag: 'https://restcountries.eu/data/esp.svg',
  }, {
    name: 'Sri Lanka',
    id: 'LKA',
    capital: 'Colombo',
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 20966000,
    latlng: [7, 81],
    area: 65610,
    translations: {
      de: 'Sri Lanka', es: 'Sri Lanka', fr: 'Sri Lanka', ja: 'スリランカ', it: 'Sri Lanka', br: 'Sri Lanka', pt: 'Sri Lanka', nl: 'Sri Lanka', hr: 'Šri Lanka', fa: 'سری‌لانکا',
    },
    flag: 'https://restcountries.eu/data/lka.svg',
  }, {
    name: 'Sudan',
    id: 'SDN',
    capital: 'Khartoum',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 39598700,
    latlng: [15, 30],
    area: 1886068,
    translations: {
      de: 'Sudan', es: 'Sudán', fr: 'Soudan', ja: 'スーダン', it: 'Sudan', br: 'Sudão', pt: 'Sudão', nl: 'Soedan', hr: 'Sudan', fa: 'سودان',
    },
    flag: 'https://restcountries.eu/data/sdn.svg',
  }, {
    name: 'Suriname',
    id: 'SUR',
    capital: 'Paramaribo',
    region: 'Americas',
    subregion: 'South America',
    population: 541638,
    latlng: [4, -56],
    area: 163820,
    translations: {
      de: 'Suriname', es: 'Surinam', fr: 'Surinam', ja: 'スリナム', it: 'Suriname', br: 'Suriname', pt: 'Suriname', nl: 'Suriname', hr: 'Surinam', fa: 'سورینام',
    },
    flag: 'https://restcountries.eu/data/sur.svg',
  }, {
    name: 'Swaziland',
    id: 'SWZ',
    capital: 'Lobamba',
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 1132657,
    latlng: [-26.5, 31.5],
    area: 17364,
    translations: {
      de: 'Swasiland', es: 'Suazilandia', fr: 'Swaziland', ja: 'スワジランド', it: 'Swaziland', br: 'Suazilândia', pt: 'Suazilândia', nl: 'Swaziland', hr: 'Svazi', fa: 'سوازیلند',
    },
    flag: 'https://restcountries.eu/data/swz.svg',
  }, {
    name: 'Sweden',
    id: 'SWE',
    capital: 'Stockholm',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 9894888,
    latlng: [62, 15],
    area: 450295,
    translations: {
      de: 'Schweden', es: 'Suecia', fr: 'Suède', ja: 'スウェーデン', it: 'Svezia', br: 'Suécia', pt: 'Suécia', nl: 'Zweden', hr: 'Švedska', fa: 'سوئد',
    },
    flag: 'https://restcountries.eu/data/swe.svg',
  }, {
    name: 'Switzerland',
    id: 'CHE',
    capital: 'Bern',
    region: 'Europe',
    subregion: 'Western Europe',
    population: 8341600,
    latlng: [47, 8],
    area: 41284,
    translations: {
      de: 'Schweiz', es: 'Suiza', fr: 'Suisse', ja: 'スイス', it: 'Svizzera', br: 'Suíça', pt: 'Suíça', nl: 'Zwitserland', hr: 'Švicarska', fa: 'سوئیس',
    },
    flag: 'https://restcountries.eu/data/che.svg',
  }, {
    name: 'Syrian Arab Republic',
    id: 'SYR',
    capital: 'Damascus',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 18564000,
    latlng: [35, 38],
    area: 185180,
    translations: {
      de: 'Syrien', es: 'Siria', fr: 'Syrie', ja: 'シリア・アラブ共和国', it: 'Siria', br: 'Síria', pt: 'Síria', nl: 'Syrië', hr: 'Sirija', fa: 'سوریه',
    },
    flag: 'https://restcountries.eu/data/syr.svg',
  }, {
    name: 'Tajikistan',
    id: 'TJK',
    capital: 'Dushanbe',
    region: 'Asia',
    subregion: 'Central Asia',
    population: 8593600,
    latlng: [39, 71],
    area: 143100,
    translations: {
      de: 'Tadschikistan', es: 'Tayikistán', fr: 'Tadjikistan', ja: 'タジキスタン', it: 'Tagikistan', br: 'Tajiquistão', pt: 'Tajiquistão', nl: 'Tadzjikistan', hr: 'Tađikistan', fa: 'تاجیکستان',
    },
    flag: 'https://restcountries.eu/data/tjk.svg',
  }, {
    name: 'Tanzania, United Republic of',
    id: 'TZA',
    capital: 'Dodoma',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 55155000,
    latlng: [-6, 35],
    area: 945087,
    translations: {
      de: 'Tansania', es: 'Tanzania', fr: 'Tanzanie', ja: 'タンザニア', it: 'Tanzania', br: 'Tanzânia', pt: 'Tanzânia', nl: 'Tanzania', hr: 'Tanzanija', fa: 'تانزانیا',
    },
    flag: 'https://restcountries.eu/data/tza.svg',
  }, {
    name: 'Thailand',
    id: 'THA',
    capital: 'Bangkok',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 65327652,
    latlng: [15, 100],
    area: 513120,
    translations: {
      de: 'Thailand', es: 'Tailandia', fr: 'Thaïlande', ja: 'タイ', it: 'Tailandia', br: 'Tailândia', pt: 'Tailândia', nl: 'Thailand', hr: 'Tajland', fa: 'تایلند',
    },
    flag: 'https://restcountries.eu/data/tha.svg',
  }, {
    name: 'Timor-Leste',
    id: 'TLS',
    capital: 'Dili',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 1167242,
    latlng: [-8.83333333, 125.91666666],
    area: 14874,
    translations: {
      de: 'Timor-Leste', es: 'Timor Oriental', fr: 'Timor oriental', ja: '東ティモール', it: 'Timor Est', br: 'Timor Leste', pt: 'Timor Leste', nl: 'Oost-Timor', hr: 'Istočni Timor', fa: 'تیمور شرقی',
    },
    flag: 'https://restcountries.eu/data/tls.svg',
  }, {
    name: 'Togo',
    id: 'TGO',
    capital: 'Lomé',
    region: 'Africa',
    subregion: 'Western Africa',
    population: 7143000,
    latlng: [8, 1.16666666],
    area: 56785,
    translations: {
      de: 'Togo', es: 'Togo', fr: 'Togo', ja: 'トーゴ', it: 'Togo', br: 'Togo', pt: 'Togo', nl: 'Togo', hr: 'Togo', fa: 'توگو',
    },
    flag: 'https://restcountries.eu/data/tgo.svg',
  }, {
    name: 'Tonga',
    id: 'TON',
    capital: "Nuku'alofa",
    region: 'Oceania',
    subregion: 'Polynesia',
    population: 103252,
    latlng: [-20, -175],
    area: 747,
    translations: {
      de: 'Tonga', es: 'Tonga', fr: 'Tonga', ja: 'トンガ', it: 'Tonga', br: 'Tonga', pt: 'Tonga', nl: 'Tonga', hr: 'Tonga', fa: 'تونگا',
    },
    flag: 'https://restcountries.eu/data/ton.svg',
  }, {
    name: 'Trinidad and Tobago',
    id: 'TTO',
    capital: 'Port of Spain',
    region: 'Americas',
    subregion: 'Caribbean',
    population: 1349667,
    latlng: [11, -61],
    area: 5130,
    translations: {
      de: 'Trinidad und Tobago', es: 'Trinidad y Tobago', fr: 'Trinité et Tobago', ja: 'トリニダード・トバゴ', it: 'Trinidad e Tobago', br: 'Trinidad e Tobago', pt: 'Trindade e Tobago', nl: 'Trinidad en Tobago', hr: 'Trinidad i Tobago', fa: 'ترینیداد و توباگو',
    },
    flag: 'https://restcountries.eu/data/tto.svg',
  }, {
    name: 'Tunisia',
    id: 'TUN',
    capital: 'Tunis',
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 11154400,
    latlng: [34, 9],
    area: 163610,
    translations: {
      de: 'Tunesien', es: 'Túnez', fr: 'Tunisie', ja: 'チュニジア', it: 'Tunisia', br: 'Tunísia', pt: 'Tunísia', nl: 'Tunesië', hr: 'Tunis', fa: 'تونس',
    },
    flag: 'https://restcountries.eu/data/tun.svg',
  }, {
    name: 'Turkey',
    id: 'TUR',
    capital: 'Ankara',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 78741053,
    latlng: [39, 35],
    area: 783562,
    translations: {
      de: 'Türkei', es: 'Turquía', fr: 'Turquie', ja: 'トルコ', it: 'Turchia', br: 'Turquia', pt: 'Turquia', nl: 'Turkije', hr: 'Turska', fa: 'ترکیه',
    },
    flag: 'https://restcountries.eu/data/tur.svg',
  }, {
    name: 'Turkmenistan',
    id: 'TKM',
    capital: 'Ashgabat',
    region: 'Asia',
    subregion: 'Central Asia',
    population: 4751120,
    latlng: [40, 60],
    area: 488100,
    translations: {
      de: 'Turkmenistan', es: 'Turkmenistán', fr: 'Turkménistan', ja: 'トルクメニスタン', it: 'Turkmenistan', br: 'Turcomenistão', pt: 'Turquemenistão', nl: 'Turkmenistan', hr: 'Turkmenistan', fa: 'ترکمنستان',
    },
    flag: 'https://restcountries.eu/data/tkm.svg',
  }, {
    name: 'Tuvalu',
    id: 'TUV',
    capital: 'Funafuti',
    region: 'Oceania',
    subregion: 'Polynesia',
    population: 10640,
    latlng: [-8, 178],
    area: 26,
    translations: {
      de: 'Tuvalu', es: 'Tuvalu', fr: 'Tuvalu', ja: 'ツバル', it: 'Tuvalu', br: 'Tuvalu', pt: 'Tuvalu', nl: 'Tuvalu', hr: 'Tuvalu', fa: 'تووالو',
    },
    flag: 'https://restcountries.eu/data/tuv.svg',
  }, {
    name: 'Uganda',
    id: 'UGA',
    capital: 'Kampala',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 33860700,
    latlng: [1, 32],
    area: 241550,
    translations: {
      de: 'Uganda', es: 'Uganda', fr: 'Uganda', ja: 'ウガンダ', it: 'Uganda', br: 'Uganda', pt: 'Uganda', nl: 'Oeganda', hr: 'Uganda', fa: 'اوگاندا',
    },
    flag: 'https://restcountries.eu/data/uga.svg',
  }, {
    name: 'Ukraine',
    id: 'UKR',
    capital: 'Kiev',
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 42692393,
    latlng: [49, 32],
    area: 603700,
    translations: {
      de: 'Ukraine', es: 'Ucrania', fr: 'Ukraine', ja: 'ウクライナ', it: 'Ucraina', br: 'Ucrânia', pt: 'Ucrânia', nl: 'Oekraïne', hr: 'Ukrajina', fa: 'وکراین',
    },
    flag: 'https://restcountries.eu/data/ukr.svg',
  }, {
    name: 'United Arab Emirates',
    id: 'ARE',
    capital: 'Abu Dhabi',
    region: 'Asia',
    subregion: 'Western Asia',
    population: 9856000,
    latlng: [24, 54],
    area: 83600,
    translations: {
      de: 'Vereinigte Arabische Emirate', es: 'Emiratos Árabes Unidos', fr: 'Émirats arabes unis', ja: 'アラブ首長国連邦', it: 'Emirati Arabi Uniti', br: 'Emirados árabes Unidos', pt: 'Emirados árabes Unidos', nl: 'Verenigde Arabische Emiraten', hr: 'Ujedinjeni Arapski Emirati', fa: 'امارات متحده عربی',
    },
    flag: 'https://restcountries.eu/data/are.svg',
  }, {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    id: 'GBR',
    capital: 'London',
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 65110000,
    latlng: [54, -2],
    area: 242900,
    translations: {
      de: 'Vereinigtes Königreich', es: 'Reino Unido', fr: 'Royaume-Uni', ja: 'イギリス', it: 'Regno Unito', br: 'Reino Unido', pt: 'Reino Unido', nl: 'Verenigd Koninkrijk', hr: 'Ujedinjeno Kraljevstvo', fa: 'بریتانیای کبیر و ایرلند شمالی',
    },
    flag: 'https://restcountries.eu/data/gbr.svg',
  }, {
    name: 'United States of America',
    id: 'USA',
    capital: 'Washington, D.C.',
    region: 'Americas',
    subregion: 'Northern America',
    population: 323947000,
    latlng: [38, -97],
    area: 9629091,
    translations: {
      de: 'Vereinigte Staaten von Amerika', es: 'Estados Unidos', fr: 'États-Unis', ja: 'アメリカ合衆国', it: "Stati Uniti D'America", br: 'Estados Unidos', pt: 'Estados Unidos', nl: 'Verenigde Staten', hr: 'Sjedinjene Američke Države', fa: 'ایالات متحده آمریکا',
    },
    flag: 'https://restcountries.eu/data/usa.svg',
  }, {
    name: 'Uruguay',
    id: 'URY',
    capital: 'Montevideo',
    region: 'Americas',
    subregion: 'South America',
    population: 3480222,
    latlng: [-33, -56],
    area: 181034,
    translations: {
      de: 'Uruguay', es: 'Uruguay', fr: 'Uruguay', ja: 'ウルグアイ', it: 'Uruguay', br: 'Uruguai', pt: 'Uruguai', nl: 'Uruguay', hr: 'Urugvaj', fa: 'اروگوئه',
    },
    flag: 'https://restcountries.eu/data/ury.svg',
  }, {
    name: 'Uzbekistan',
    id: 'UZB',
    capital: 'Tashkent',
    region: 'Asia',
    subregion: 'Central Asia',
    population: 31576400,
    latlng: [41, 64],
    area: 447400,
    translations: {
      de: 'Usbekistan', es: 'Uzbekistán', fr: 'Ouzbékistan', ja: 'ウズベキスタン', it: 'Uzbekistan', br: 'Uzbequistão', pt: 'Usbequistão', nl: 'Oezbekistan', hr: 'Uzbekistan', fa: 'ازبکستان',
    },
    flag: 'https://restcountries.eu/data/uzb.svg',
  }, {
    name: 'Vanuatu',
    id: 'VUT',
    capital: 'Port Vila',
    region: 'Oceania',
    subregion: 'Melanesia',
    population: 277500,
    latlng: [-16, 167],
    area: 12189,
    translations: {
      de: 'Vanuatu', es: 'Vanuatu', fr: 'Vanuatu', ja: 'バヌアツ', it: 'Vanuatu', br: 'Vanuatu', pt: 'Vanuatu', nl: 'Vanuatu', hr: 'Vanuatu', fa: 'وانواتو',
    },
    flag: 'https://restcountries.eu/data/vut.svg',
  }, {
    name: 'Venezuela (Bolivarian Republic of)',
    id: 'VEN',
    capital: 'Caracas',
    region: 'Americas',
    subregion: 'South America',
    population: 31028700,
    latlng: [8, -66],
    area: 916445,
    translations: {
      de: 'Venezuela', es: 'Venezuela', fr: 'Venezuela', ja: 'ベネズエラ・ボリバル共和国', it: 'Venezuela', br: 'Venezuela', pt: 'Venezuela', nl: 'Venezuela', hr: 'Venezuela', fa: 'ونزوئلا',
    },
    flag: 'https://restcountries.eu/data/ven.svg',
  }, {
    name: 'Viet Nam',
    id: 'VNM',
    capital: 'Hanoi',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 92700000,
    latlng: [16.16666666, 107.83333333],
    area: 331212,
    translations: {
      de: 'Vietnam', es: 'Vietnam', fr: 'Viêt Nam', ja: 'ベトナム', it: 'Vietnam', br: 'Vietnã', pt: 'Vietname', nl: 'Vietnam', hr: 'Vijetnam', fa: 'ویتنام',
    },
    flag: 'https://restcountries.eu/data/vnm.svg',
  }, {
    name: 'Yemen',
    id: 'YEM',
    capital: "Sana'a",
    region: 'Asia',
    subregion: 'Western Asia',
    population: 27478000,
    latlng: [15, 48],
    area: 527968,
    translations: {
      de: 'Jemen', es: 'Yemen', fr: 'Yémen', ja: 'イエメン', it: 'Yemen', br: 'Iêmen', pt: 'Iémen', nl: 'Jemen', hr: 'Jemen', fa: 'یمن',
    },
    flag: 'https://restcountries.eu/data/yem.svg',
  }, {
    name: 'Zambia',
    id: 'ZMB',
    capital: 'Lusaka',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 15933883,
    latlng: [-15, 30],
    area: 752612,
    translations: {
      de: 'Sambia', es: 'Zambia', fr: 'Zambie', ja: 'ザンビア', it: 'Zambia', br: 'Zâmbia', pt: 'Zâmbia', nl: 'Zambia', hr: 'Zambija', fa: 'زامبیا',
    },
    flag: 'https://restcountries.eu/data/zmb.svg',
  }, {
    name: 'Zimbabwe',
    id: 'ZWE',
    capital: 'Harare',
    region: 'Africa',
    subregion: 'Eastern Africa',
    population: 14240168,
    latlng: [-20, 30],
    area: 390757,
    translations: {
      de: 'Simbabwe', es: 'Zimbabue', fr: 'Zimbabwe', ja: 'ジンバブエ', it: 'Zimbabwe', br: 'Zimbabwe', pt: 'Zimbabué', nl: 'Zimbabwe', hr: 'Zimbabve', fa: 'زیمباوه',
    },
    flag: 'https://restcountries.eu/data/zwe.svg',
  },
];
